### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by devendragera** [imodeljs/imodeljs#10]
We are trying to run the simple-viewer-app which you have provided on github, but get the loginfailed error when trying to open the sample iModel. 

![loginissue_1](https://user-images.githubusercontent.com/10633255/48250238-87d25000-e3f5-11e8-9f3b-01a3ff331f04.jpg)

We have made changes in configuration.ts as per your documentation

![loginissue_2](https://user-images.githubusercontent.com/10633255/48250237-87d25000-e3f5-11e8-8602-48add1a49b20.jpg)
Can you please advise on the error? Also, where do we upload .i.dgn (ie iModels) to be able to access this model? Do you have sample iModels for us to try out?

Thanks in advance.

**Comment by LabyrinthTechnology** [comment]
Did you ask the test project was created for you as described in developer registration?

**Comment by devendragera** [comment]
Thanks for your response.

Yes, I did receive the confirmation about the test project- as below:

-----

Sample IModel Project was created with Project Name: Test Project 1, and IModel Name: Test Project 1

**Comment by LabyrinthTechnology** [comment]
> Yes, I did receive the confirmation about the test project

And do you see it in your project information? After my project was created, there were two issues (see #3): I did not see the project in my projects list and when I found it, iModels were not accessible / displayed from some reasons.

![imodeljs-project-external](https://user-images.githubusercontent.com/8292864/48255370-c4f60c80-e40c-11e8-9de8-c6ff36a9cfe4.jpg)

**Comment by roopsaini** [comment]
Hi @devendragera,

It looks like the root cause for this error was the same as for issue #3 . You should be able to access the iModel now. We are currently trying to ensure other users don't run into this issue.

Thanks,
Roop

**Comment by devendragera** [comment]
Thanks, Roop. It is working now. We will be exploring imodel / imodeljs further.

Devendra
