### ISSUE TITLE
possible to use a local model file?

### ISSUE THREAD

**Issue by spookyfox** [imodeljs/imodeljs#1017]
Hi,

I would like to give this library a try but w/o to use any cloud services for the time being. What do I need to do to use it with local model files? Thanks in advance, Henrik
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Developing-a-web-viewer---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/develop-web-viewer/

**Comment by pmconne** [comment]
If you go back to the [tutorials page](https://www.itwinjs.org/learning/tutorials/) you'' find tutorials for [creating a local iModel](https://www.itwinjs.org/learning/tutorials/create-test-imodel-offline/) and [building a desktop (offline) viewer](https://www.itwinjs.org/learning/tutorials/develop-desktop-viewer/).
