### ISSUE TITLE
Get different CAD models into current position 

### ISSUE THREAD

**Issue by Simplefair-China** [imodeljs/imodeljs#1066]
Sir, 

One of imodel great function is merging different into one imodel file. My question is how to place the different CAD models  into current position. For example, I try to assemble a Revit file（architectural building) with a CATIA file (Mechanical equipment) together and build one imodel file just like Autodesk Navisworks can assemble different CAD model into one file.

Thanks in advance.

**Comment by Simplefair-China** [comment]
Sorry, maybe assemble a Revit file with a IFC and a Autodesk Civil 3D model into one imodel.

**Comment by pmconne** [comment]
Have you looked at [iTwin Synchronizer](https://www.bentley.com/en/products/product-line/digital-twins/itwin-synchronizer)? As described on that page it supports Revit and Civil 3d.

**Comment by Simplefair-China** [comment]
Thanks for quick response. My customer try to assemble a Revit and CATIA file together, but Snapshot don't support CATIA. So I input CATIA into Navisworks and try to assemble them into one imodel, but I can't place the Naviworks file into right position. So any suggestion?

Thanks a lot.

**Comment by pmconne** [comment]
> So any suggestion?

Yes - [iTwin Synchronizer](https://www.bentley.com/en/products/product-line/digital-twins/itwin-synchronizer). Have you looked at it?

Beyond that, @abeesh and @jffmarker.

**Comment by abeesh** [comment]
In order for the data to align you will have to use a common alignment to bring data together. Typically this involves ensuring they share a coordinate system or the same location in space. For more information, please see 
[Publishing revit files with known global location](https://communities.bentley.com/products/digital-twin-cloud-services/itwin-services/w/synchronization-wiki/53140/publishing-revit-files-with-known-global-location)

**Comment by Simplefair-China** [comment]
Thank for your help and support. I can place most of different CAD model into right position. But I still can not position the Navisworks model. Any suggestion?

Thanks a lot!

**Comment by jffmarker** [comment]
Do you have access to the full Navisworks App? You can right-click on the root node of the selection tree, select Units and Transform..., and that should let you shift the NWD data (and then run it through the Connector again).

**Comment by Simplefair-China** [comment]
Thanks a lot!
