### ISSUE TITLE
Having Difficulties to run frontend and backend on seperate ports

### ISSUE THREAD

**Issue by hsanand61564** [imodeljs/imodeljs#107]
If we are running the frontend and backend at the same server it works perfectly fine, but when we are trying to run the backend and frontend on different servers it gives us 500(Internal Server Error).

**Comment by hsanand61564** [comment]
Attaching all screenshots for your reference

Initialize Client

![Initializ Client](https://user-images.githubusercontent.com/60655118/90433039-d6437100-e0e8-11ea-8718-51c879c6b8df.PNG)

Initialize backend

![Initializ backend](https://user-images.githubusercontent.com/60655118/90433044-d80d3480-e0e8-11ea-8bdd-bcbf0118bab6.PNG)

OpenSnapshot

![OpenSnapshot](https://user-images.githubusercontent.com/60655118/90433047-d8a5cb00-e0e8-11ea-8a6e-e7a4f2301e7c.PNG)

Console Error
![Console  Error](https://user-images.githubusercontent.com/60655118/90433298-4520ca00-e0e9-11ea-8b95-71d2f5b8e26d.PNG)


Any help from you would be really appreciated.

**Comment by swbsi** [comment]
Can you share some code for your express server configuration?
Is it possible that the backend server is still listening on the old port?

**Comment by hsanand61564** [comment]
![Capture](https://user-images.githubusercontent.com/60655118/90552793-fd657580-e1b0-11ea-8d90-ebfbebc1bee8.PNG)

**Comment by hsanand61564** [comment]
the backend server is running on the correct port, I don't think that's the issue

**Comment by swbsi** [comment]
Can you share details of the 500 server response then?
The response body (accessible via the network tab in devtools) should contain JSON that will help track this down.

**Comment by hsanand61564** [comment]
Here are the screenshots from the network tab--> We are not getting the JSON in response

![1](https://user-images.githubusercontent.com/60655118/90634565-83cb9700-e245-11ea-97ba-8f3e8c85ca79.PNG)

![2](https://user-images.githubusercontent.com/60655118/90634568-84642d80-e245-11ea-9593-42062e9dec8e.PNG)

![3](https://user-images.githubusercontent.com/60655118/90634564-8201d380-e245-11ea-80af-784394f93e8c.PNG)

**Comment by ColinKerr** [comment]
@hsanand61564 would you be willing to upload your code to GitHub so we could look at what you're doing in more detail?

**Comment by swbsi** [comment]
@hsanand61564 Can you also confirm that all your servers are running on localhost?

**Comment by swbsi** [comment]
@hsanand61564 Can you also confirm that all your servers are running on localhost?

**Comment by swbsi** [comment]
@hsanand61564 Can you also confirm that all your servers are running on localhost?

**Comment by hsanand61564** [comment]
@swbsi : yeah all the servers are running on localhost
@ColinKerr : I need to discuss with my team and let u know for this.

**Comment by swbsi** [comment]
Can you put a try/catch around the openFile call in your frontend code and set a breakpoint (or log) in the error case?

There is a non-zero content length on the 500 server response so there should be some info available.

________________________________

**Comment by hsanand61564** [comment]
I tried putting up try/catch block and just gave me this error

issue inside snapshot model --> SyntaxError: Unexpected token o in JSON at position 1

**Comment by swbsi** [comment]
@hsanand61564 Can you set a breakpoint here in WebAppRpcRequest.loadText?

https://github.com/imodeljs/imodeljs/blob/0362e29ec38930bf279f3f6e1de16788ad02ffaf/core/common/src/rpc/web/WebAppRpcRequest.ts#L267

The error suggests that our backend RPC logic did not process the request and another layer in the backend server stack responded.

**Comment by swbsi** [comment]
@hsanand61564 Did you have a chance to try the breakpoint in WebAppRpcRequest.loadText?
The code in that function loads the backend response that will help track this down.

**Comment by hsanand61564** [comment]
@swbsi And I tried putting up the debugger suggested by you and I suppose the logic is working perfectly fine when on the same server but not working in the same manner when used on a different server. This is because when we are trying to use the same thing on the same server it is working fine but when we are using the backend on a different server it is producing this kind of error.

**Comment by swbsi** [comment]
@hsanand61564 Do you still hit the breakpoint in the different server scenario?
If so, can you paste in the value that will be assigned on line 267 here?

**Comment by swbsi** [comment]
@hsanand61564 Can you also paste in the full call stack for the SyntaxError that is caught by your try/catch?

**Comment by PKASHYAP-BEC** [comment]
Hello, 

I am facing this issue and i am getting this error on line 94 of RpcInvocation.js file. 

![image](https://user-images.githubusercontent.com/60220061/91585214-626b5900-e971-11ea-9813-800bc6092bd4.png)

my request value is below 

{
  id: "b15530fc-97c8-4328-a63f-157425ad69d5",
  applicationId: "2686",
  applicationVersion: "",
  sessionId: "fc98f2d6-8659-402d-b395-055eac0413d2",
  authorization: undefined,
  userId: undefined,
  operation: {
    interfaceDefinition: "SnapshotIModelRpcInterface",
    operationName: "openFile",
    interfaceVersion: "2.0.0",
  },
  method: "POST",
  path: "/viewerapp/v1.0/mode/2/context//imodel/undefined/SnapshotIModelRpcInterface-2.0.0-openFile",
  parameters: {
    objects: {
    },
    data: [
    ],
  },
  caching: 0,
  ip: "::1",
}


**Please suggest because at this point of time when using diffent port my request parameter is empty and i think this is causing the issue.**

**Comment by swbsi** [comment]
@PKASHYAP-BEC Can you set a breakpoint here on the backend and log the value of req.path and req.body?

https://github.com/imodeljs/imodeljs/blob/0362e29ec38930bf279f3f6e1de16788ad02ffaf/core/common/src/rpc/web/WebAppRpcRequest.ts#L63

**Comment by PKASHYAP-BEC** [comment]
Sir , 

As per your suggestion , 

req.path="/viewerapp/v1.0/mode/2/context//imodel/undefined/SnapshotIModelRpcInterface-2.0.0-openFile"
and req.body={}

**Comment by swbsi** [comment]
I just noticed back in your express server code that you are using bodyParser.json. That is not supported right now. Please switch to bodyParser.text and log the values again (please also log req.headers).

**Comment by PKASHYAP-BEC** [comment]
Sir , 

here are the requested details, but the body-parser solution worked this time.  Thank you for your help to get this fixed.

req.path:"/viewerapp/v1.0/mode/2/context//imodel/undefined/SnapshotIModelRpcInterface-2.0.0-openFile"
req.body:"[\"C:\\\\\\\\Projects\\\\\\\\BIM\\\\\\\\spool.bim\"]"
req.headers:{
  host: "localhost:34005",
  connection: "keep-alive",
  "content-length": "38",
  "x-correlation-id": "2b7f84d0-8fb3-4003-8cd4-6dd203006381",
  "x-application-version": "",
  "x-application-id": "2686",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
  "x-session-id": "04257791-3188-4b1c-885b-41af214ad748",
  "content-type": "text/plain",
  accept: "*/*",
  origin: "http://localhost:3000",
  "sec-fetch-site": "same-site",
  "sec-fetch-mode": "cors",
  "sec-fetch-dest": "empty",
  referer: "http://localhost:3000/viewer",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "en-US,en;q=0.9,hi;q=0.8",
}

**Comment by swbsi** [comment]
Excellent, glad to hear everything is working now. Best of luck with your project.
