### ISSUE TITLE
OPC UA server?

### ISSUE THREAD

**Issue by johngillerman** [imodeljs/imodeljs#11]
How about adding support for OPC UA?   An OPC UA server on the imodel hub would publish OPC UA model change events.  You could use Node OPCUA...

**Comment by kabentley** [comment]
sounds like a good idea to me. We'll pass it along to the iModelHub guys.

Do you use Node OPCUA yourself?

**Comment by johngillerman** [comment]
Yes, but the issue is there is no good infrastructure for managing OPC UA models across time.

See: https://autodeskuniversity.smarteventscloud.com/connect/sessionDetail.ww?SESSION_ID=227503

iModelHub seems very well suited to this use case.

**Comment by eligijusm** [comment]
iModelHub Service itself is synchronization platform for distributed iModel copies using ChangeSets. It doesn't provide a way to read/write data in iModel directly, thus it can't integrate OPC UA directly. However, OPC UA can be implemented as separate iTwin service based on iModel.js that leverages iModelHub ability to store history. We will add this to our considerations list.

I also want to highlight that iModel.js is platform open to whole global development community and we are encouraging everyone to help us build and improve it based on your needs faster, whether it is through the feedback or direct involvement in the code.
