### ISSUE TITLE
iModel.js 2.5.3 bug reporting (about SnapshotIModelRpcInterface ...)

### ISSUE THREAD

**Issue by Myzik-Dev** [imodeljs/imodeljs#111]
iModel.js 2.5.3 library seems to have bugs.

There is no problem in the old version, 
but in that version, an error message [An RPC interface impression class for "SnapshotIModelRpcInterface" is not registered.] appears. (runtime error)

**Comment by Myzik-Dev** [comment]
export function getSupportedRpcs(): RpcInterfaceDefinition[] {
  return [
    IModelReadRpcInterface,
    IModelTileRpcInterface,
    PresentationRpcInterface,
    SnapshotIModelRpcInterface, // registered
  ];
}

**Comment by Myzik-Dev** [comment]
I'd like to ask one more question.
Can I render 'Reality Mesh' using 'SnapshotConnection'?

**Comment by namsancow** [comment]
I don't think so

**Comment by Myzik-Dev** [comment]
I'd like to ask one more question.
Can I render 'Reality Mesh' using 'SnapshotConnection'?

**Comment by kabentley** [comment]
As to the error you're seeing, make sure you have the correct version of @bentley/imodeljs-backend installed, and that you've called IModelHost.startup(). If you want to debug it, you can see that interface getting registered [here](https://github.com/imodeljs/imodeljs/blob/75c655b44a5d24e9e8f85825192341fa0802a989/core/backend/src/IModelHost.ts#L415-L433)

Yes you should be able to render reality meshes from a desktop app using a local snapshot iModel, as long as you have a network connection and are authenticated to the reality data server. That is quite common.

**Comment by Myzik-Dev** [comment]
I checked the installation version of @bentley/imodeljs-backend.
The correct version was installed as '@bentley/imodeljs-backend@2.5.3'.

I asked the question because I compiled the sample source of imodeljs and had the same runtime error as my source.

==========================================================================

**[rpcs.ts]**
export function getSupportedRpcs(): RpcInterfaceDefinition[] {

  return [
    IModelReadRpcInterface,
    IModelTileRpcInterface,
    PresentationRpcInterface,
    SnapshotIModelRpcInterface,
  ];
}

**[backend/main.ts]**

(async () => {
  try {
    // Initialize iModelHost
    await IModelHost.startup();

    // Initialize Presentation
    Presentation.initialize();

    // Get platform-specific initialization function
    let init: (rpcs: RpcInterfaceDefinition[]) => void;
    if (electron) {
      init = (await import("./electron/main")).default;
    } else {
      init = (await import("./web/BackendServer")).default;
    }

    // Get RPCs supported by this backend
    const rpcs = getSupportedRpcs();

    // Invoke platform-specific initialization
    init(rpcs);
  } catch (error) {
    Logger.logError(AppLoggerCategory.Backend, error);
    process.exitCode = 1;
  }
})(); 

**[frontend/rpc.ts]**

export function initRpc(rpcParams?: BentleyCloudRpcParams): RpcConfiguration {
  let config: RpcConfiguration;
  const rpcInterfaces = getSupportedRpcs();
  if (ElectronRpcConfiguration.isElectron) {
    // initializes RPC for Electron
    config = ElectronRpcManager.initializeClient({}, rpcInterfaces);
  } else {
    // initialize RPC for web apps
    if (!rpcParams)
      rpcParams = { info: { title: "sample-app", version: "v1.0" }, uriPrefix: "http://localhost:3001" };
    config = BentleyCloudRpcManager.initializeClient(rpcParams, rpcInterfaces);
  }
  return config;
}

==========================================================================

**Comment by kabentley** [comment]
are you using Electron or a web app with localhost?

**Comment by swbsi** [comment]
@Myzik-Dev The core RPC implementations are registered during IModelHost.startup. The error you are experiencing is often a sign that something went wrong during that function call.

Can you put a try/catch around your awaited call to startup and verify if any errors occur?

**Comment by Myzik-Dev** [comment]
> Only web app

**Comment by Myzik-Dev** [comment]
> @Myzik-Dev The core RPC implementations are registered during IModelHost.startup. The error you are experiencing is often a sign that something went wrong during that function call.
> 
> Can you put a try/catch around your awaited call to startup and verify if any errors occur?

There was no error found in try/catch.

**Comment by Myzik-Dev** [comment]
> are you using Electron or a web app with localhost?

Only web app

**Comment by calebmshafer** [comment]
@Myzik-Dev can you try iModel.js 2.6.0 that was just released and see if you're still able to reproduce the issue?

**Comment by Myzik-Dev** [comment]
> iModel.js 2.6.0

It works well in iModel.js 2.6.0. 👍 
Thank you for taking care of it quickly.
