### ISSUE TITLE
Can 'tileSizeThreshold' be modified at the source level?

### ISSUE THREAD

**Issue by Myzik-Dev** [imodeljs/imodeljs#112]
A warning message 'Tile size (in bytes) lager than specified thread' is displayed.

Can 'tileSizeThreshold' be modified at the source level?

**Comment by pmconne** [comment]
You can configure this other and parameters via the [IModelHostConfiguration](https://github.com/imodeljs/imodeljs/blob/75c655b44a5d24e9e8f85825192341fa0802a989/core/backend/src/IModelHost.ts#L173) supplied to `IModelHost.startup()`.
Please consider using the [discussions page](https://github.com/imodeljs/imodeljs/discussions) for asking questions.
