### ISSUE TITLE
Code state is invalid

### ISSUE THREAD

**Issue by ashish-srivastava-dev** [imodeljs/imodeljs#1153]
Sometimes I get this error: 

Code state is invalid.
iModelHub.CodeStateInvalid: Code state is invalid.

In which scenarios it comes?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Code---imodeljs-common-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/imodeljs-common/codes/code/?term=code+state

**Comment by pmconne** [comment]
You are going to need to provide more details.

**Comment by ashish-srivastava-dev** [comment]
It comes while running a connector to synchronize data with iModel and in saving / pushing changes to iModelhub.

**Comment by azonys** [comment]
Changes between some code states are not allowed in iModelHub (see table below). Which connector are you running?

Code state meanings:

- 0 - 'Available'. Codes with this state are not persisted in the database. Code that is updated to 'Available' state is deleted from the database;
- 1 - 'Reserved'. Code is reserved by the briefcase, no one else is allowed to change its state;
- 2 - 'Used'. Code is used in the ChangeSet committed to the server;
- 3 - 'Retired'. Retired code can't be reserved or used. It can only be deleted (or updated to 'Available' state) and then reserved again.

Table of code state transitions:
From state | To state | Allowed | Briefcase
-- | -- | -- | --
Available | Available | **No** |  
Available | Reserved | Yes | Any
Available | Used | Yes | Any
Available | Retired | Yes | Any
Reserved | Available | Yes | Only owner
Reserved | Reserved | Yes | Only owner
Reserved | Used | Yes | Only owner
Reserved | Retired | Yes | Only owner
Used | Available | Yes | Any
Used | Reserved | Yes | Any
Used | Used | Yes | Any
Used | Retired | Yes | Any
Retired | Available | Yes | Any
Retired | Reserved | **No** |  
Retired | Used | **No** |  
Retired | Retired | Yes | Any
