### ISSUE TITLE
How can Reality Mesh be rendered using imodeljs?

### ISSUE THREAD

**Issue by Myzik-Dev** [imodeljs/imodeljs#116]
Is a dedicated server (such as a caesium server or S3MXECPlugin Server) required for a Reality mesh file (.3xm, 3.3sm)?

Or is it possible to work with imodeljs with simple file hosting?

**Comment by pmconne** [comment]
Let's head over to the [Discussions](https://github.com/imodeljs/imodeljs/discussions) page where we can talk about how to convert your reality mesh to a 3D tileset, how to access it from iModel.js, etc.

**Comment by pmconne** [comment]
You may find some of the information in [this issue](https://github.com/imodeljs/imodeljs/issues/110) relevant.
