### ISSUE TITLE
Empty Views

### ISSUE THREAD

**Issue by roopksaini** [imodeljs/imodeljs#117]
Hello,

I've been supporting a developer who ran into a recurring issue: Some iModels are showing up empty in the sample apps. It looks like this happens when the default view doesn't have any models in it. I found some design review code as a solution for now. Is there any other convenient way to create a default view that contains all models within an iModel?

Thanks,
Roop

**Comment by ramanujam-raman** [comment]
There currently isn't. Unfortunately the the core team doesn't have this on the backlog. Would you be willing to create an API from the code you are sharing as the solution?

**Comment by roopksaini** [comment]
Sure, I can do that.

**Comment by roopksaini** [comment]
The API has been pushed. 
 
Links to:
-  [Blog](https://medium.com/imodeljs/is-it-open-999fbb0dbb4)
-  APIs: [ViewCreator3d](https://github.com/imodeljs/imodeljs/blob/ac8a4a399238c8b0a83399cd14c9ca9880276536/core/frontend/src/ViewCreator3d.ts) | [ViewCreator2d](https://github.com/imodeljs/imodeljs/blob/ac8a4a399238c8b0a83399cd14c9ca9880276536/core/frontend/src/ViewCreator3d.ts)
