### ISSUE TITLE
Is there an API that can capture a screen shot of a rendered bim file?

### ISSUE THREAD

**Issue by Myzik-Dev** [imodeljs/imodeljs#118]
I tried to implement it myself because it seems that API is not supplied, but it is not easy because it is WebGL based.

Is there an API that can capture a screen shot of a rendered bim file?

**Comment by kabentley** [comment]
Did you look at [Viewport.readImage](https://www.imodeljs.org/reference/imodeljs-frontend/views/viewport/readimage/)?

**Comment by Myzik-Dev** [comment]
> Did you look at [Viewport.readImage](https://www.imodeljs.org/reference/imodeljs-frontend/views/viewport/readimage/)?

It works well.
Thank you for your advice. 👍

**Comment by kabentley** [comment]
Glad to help. 

Not a big deal, but please consider using the [Discussions](https://github.com/imodeljs/imodeljs/discussions) page for asking questions (issues are generally intended for tracking "problems").
