### ISSUE TITLE
How can we upload a new .i.dgn model into iModelHub?

### ISSUE THREAD

**Issue by rachitsakhidas** [imodeljs/imodeljs#12]
Hi,

How can we upload a new .i.dgn model into iModelHub?

Thanks in advance

**Comment by rachitsakhidas** [comment]
Hi,

Thanks for the prompt reply.

I want to upload from Bentley Cloud Services from below mentioned area 

![imodel-projectwise](https://user-images.githubusercontent.com/5895202/48483501-98d9f180-e839-11e8-84b2-c7c65c1bff21.JPG)
![imodel-imodelswise](https://user-images.githubusercontent.com/5895202/48483500-98d9f180-e839-11e8-8fdf-d7f1db5b73e5.JPG)

``


Thanks in advance

**Comment by LabyrinthTechnology** [comment]
I do not quite understand your question and what do you want to achieve :-(

Your first question was about to upload .i.dgn file to iModelHub (which is a service), but what do you mean by _upload from Bentley Cloud Services_?

You picture seems to displays iModelHub, there is Test Project 1, which I assume is a sample project created for you for testing purposes. So what data do you want to move/copy/upload to what repository?

Be aware iModelHub **is not** a file repository, but "time based service" storing data changes, so to upload a file makes no sense in this case. This is a responsibility of [iModel Bridges](https://imodeljs.github.io/iModelJs-docs-output/learning/imodel-bridges/) to convert data organized in files into a proper format and store it in iModelHub. Of course you can do the same using iModelJs library, I recommend to see e.g. [iModel creation](https://imodeljs.github.io/iModelJs-docs-output/learning/imodelhub/imodels/createimodel/?term=imodel) documentation.

Regards,

  Jan

**Comment by rachitsakhidas** [comment]
Hi,

Thanks for the reply.

I just want to upload or create iModel.js based file so can you please guide us how can i achieve this.

I want to test other file rather than sample test file and also want to know how can we test other iModelJs supported file.


Thanks in advance

**Comment by LabyrinthTechnology** [comment]
> I just want to upload or create iModel.js based file so can you please guide us how can i achieve this.

Read [documentation](https://imodeljs.github.io/iModelJs-docs-output//), both learning and API and start to try to write own code. I guess no other advice exist now as it's still quite early development state, so there is no library with many examples available.

In my opinion (and it's what I plan also for myself) the best approach is to start from simple code (e.g. to create and read local / offline iModel), go to online (own code how to login, authenticate, read data from prepared model, modify them, post them back) and in the final step to create own model in prepared project/repository.

My feeling a crucial thing is to understand data oranization, which is not project and files inside.

> and also want to know how can we test other iModelJs supported file.

It was discussed several times already (did you read all existing issues in this repository, including closed ones?) and I also wrote it: The only format supported by iModelJs is i-model 2.0. There are no _other supported formats_.

Regards,

  Jan

**Comment by weiweilinlin** [comment]
hi i cannot upload the imodel file to the iModelHub Too! but can  upload to  the shared file library,however do not works,can not open by this demo

**Comment by roopsaini** [comment]
We understand the need to access your own data using iModel.js. Our team is currently working on a solution.

Thanks,
Roop

**Comment by candcconsulting** [comment]
> Hi,
> Thanks for the reply.
> I just want to upload or create iModel.js based file so can you please guide us how can i achieve this.
> I want to test other file rather than sample test file and also want to know how can we test other iModelJs supported file.
> Thanks in advance

You saw there is a sinlge upload, but please reach out to me, there are many ways of uploading data and we would like to review the type of data you have and how often you want to update the data.


Currently we are bridging projects using i.dgn and Bentley Connect Edition applications, Revit, SmartPlant but there are other bridges that are being deployed.

**Comment by sainiroop** [comment]
Please see #57 .
