### ISSUE TITLE
Combined Reality Mesh + MicroStation Modeling is not displayed on Snapshopt mode ver 2.6.4

### ISSUE THREAD

**Issue by namsancow** [imodeljs/imodeljs#122]
I have just upgraded ver 2.6.4.
However, unfortunately  the combined Reality Mesh + MicroStation Model is not displayed on Snapshot mode of ver 2.6.4.
And interestingly enough only the Reality Mesh model  is well displayed on Snapshot mode of ver 2.6.4.
And MicroStation Model is also well displayed on Snapshot mode of ver 2.6.4.
I make some solid model in MicroStation file and attach the Reality Mesh into this file.
Publishing process for the iModel 2.0 has no problem. 
However, snapshot mode of imodeljs 2.6.4 only shows the empty skybox.

**Comment by pmconne** [comment]
Is there any output in the browser console, and if so can you copy-paste it here please?
