### ISSUE TITLE
Resizing viewer causes ResizeObserver loop limit to exceed

### ISSUE THREAD

**Issue by aruniverse** [imodeljs/imodeljs#1241]
**Describe the bug**
When resizing our imodeljs spa (bootstrapped with the itwin-viewer), we get an error about the ResizeObserver loop limit exceeded

**To Reproduce**
In ui-test-app
1. Add a global error handler to alert the error
1. Set UiFrameworkVersion="1" on Viewer component
1. Resize browser window a bit

Note, this doesn't seem to be an issue with UiFrameworkVersion 2.

- Browser:  Chrome
- iModel.js Version: 2.14 (I expect its been around for a lot longer)

**Comment by NancyMcCallB** [comment]
I've reproduced this in our test app and I'm trying to isolate the problem.
