### ISSUE TITLE
Facing issue while compiling the code

### ISSUE THREAD

**Issue by hsanand61564** [imodeljs/imodeljs#127]
I am getting an error when I am trying to bundle my code, It is just related to a semicolon in some .scss file. 
I would be really thankful if you could fix the same.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/60655118/96454224-2fd73180-1239-11eb-8513-cf3df8a2e583.png)

**Comment by NancyMcCallB** [comment]
I don't know why this syntax problem is not causing us any errors when we build. Could you tell me your:

 - iModel.js version
 - React-scripts  version
 - webpack version
 - node-sass version

so that we can try to find out?

I'll file a bug and get the scss files fixed ASAP.

Thank you!

**Comment by hsanand61564** [comment]
@NancyMcCallB Following is the list of versions that we are using

iModel.js version : "@bentley/ui-components": "^2.7.1",
React-scripts version :  "@bentley/react-scripts": "^3.4.4"
webpack version : "webpack": "^4.44.2",
node-sass version : "node-sass": "^4.14.1",

It would be really helpful if the scss file gets a fix

**Comment by hsanand61564** [comment]
@NancyMcCallB Any update on this issue?
Any help would be really appreciated.

**Comment by calebmshafer** [comment]
@hsanand61564 would you be able to try using node-sass@4.13.1 and webpack@4.42.0?  These are the versions we routinely test with and should hopefully work.

In the meantime, @NancyMcCallB is working on a fix and should in our 2.8.0 release which is expected out in the next day or two.

**Comment by NancyMcCallB** [comment]
Indeed, I scanned all the scss files for missing semicolons and committed the fix for the 2.8 build.

**Comment by hsanand61564** [comment]
@NancyMcCallB @calebmshafer Thanks for the help we are eagerly waiting for the 2.8 build

**Comment by hsanand61564** [comment]
@NancyMcCallB  @calebmshafer Hi Team, any update on the 2.8 build

**Comment by calebmshafer** [comment]
@hsanand61564 we should be releasing it in the next few hours. Performing final testing on it now before the release.

**Comment by calebmshafer** [comment]
@hsanand61564 iModel.js 2.8.0 has been released. Can you give it another try?

**Comment by hsanand61564** [comment]
@calebmshafer thanks for resolving the issue with the new build.
