### ISSUE TITLE
Failed to run rush install on tag 2.14.4 for the package checksum unmatch

### ISSUE THREAD

**Issue by bvboca** [imodeljs/imodeljs#1291]
**Describe the bug**
Rush install failed for the checksum unmatched

node_modules/.pnpm/registry.npmjs.org/core-js/3.9.1/node_modules/core-js: Running postinstall script...
node_modules/.pnpm/registry.npmjs.org/core-js/3.9.1/node_modules/core-js: Running postinstall script, done in 242ms
node_modules/.pnpm/registry.npmjs.org/core-js-pure/3.9.1/node_modules/core-js-pure: Running postinstall script, done in node_modules/.pnpm/registry.npmjs.org/dtrace-provider/0.8.8/node_modules/dtrace-provider: Running install script, done inode_modules/.pnpm/registry.npmjs.org/@bentley/imodeljs-native/2.14.7/node_modules/@bentley/imodeljs-native: Running postinstall script, failed in 2mpmjs.org/core-js/2.6.12/node_modules/core-js: Running postinstall script, done in 205ms
.../@bentley/imodeljs-native postinstall$ node ./installNativePlatform.js
│ npm install --no-save @bentley/imodeljs-win32-x64@2.14.7
│ C:\codezone\imodeljs-release-2.14.4\common\temp\node_modules\.pnpm\registry.npmjs.org\@bentley\imodeljs-native\2.14.
│       throw error;
│       ^
│ Error: Command failed: npm install --no-save @bentley/imodeljs-win32-x64@2.14.7
│ npm ERR! code EINTEGRITY
│ npm ERR! sha512-4QsFY/7vav1acsOj8xyLFuUVsJXA6m4t4u2Vyo6EJkj6p23YBSZhx80wfO8+d0lOYY0K1zgGP0Ll7rAhAi4Bjg== integrity c
│ npm ERR! A complete log of this run can be found in:
│ npm ERR!     C:\Users\nick\AppData\Roaming\npm-cache\_logs\2021-04-28T08_17_33_139Z-debug.log
│     at ChildProcess.exithandler (child_process.js:308:12)
│     at ChildProcess.emit (events.js:314:20)
│     at maybeClose (internal/child_process.js:1022:16)
│     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
│   killed: false,
│   code: 1,
│   signal: null,
│   cmd: 'npm install --no-save @bentley/imodeljs-win32-x64@2.14.7'
│ }
└─ Failed in 2m
node_modules/.pnpm/registry.npmjs.org/core-js/2.6.12/node_modules/core-js: Running postinstall script, done in 205ms
node_modules/.pnpm/registry.npmjs.org/highlight.js/9.18.5/node_modules/highlight.js: Running postinstall script, done in 155ms
node_modules/.pnpm/registry.npmjs.org/nodemon/2.0.7/node_modules/nodemon: Running postinstall script, done in 470ms
node_modules/.pnpm/registry.npmjs.org/puppeteer/5.3.1/node_modules/puppeteer: Running install script...
node_modules/.pnpm/registry.npmjs.org/typemoq/2.1.0/node_modules/typemoq: Running postinstall script, done in 147ms
 ERROR  Command failed with exit code 1.

------------------------------rush install log--------------------
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@bentley%2fimodeljs-win32-x64 4143ms (from cache)
8 silly fetchPackageMetaData error for @bentley/imodeljs-win32-x64@2.14.7 sha512-4QsFY/7vav1acsOj8xyLFuUVsJXA6m4t4u2Vyo6EJkj6p23YBSZhx80wfO8+d0lOYY0K1zgGP0Ll7rAhAi4Bjg== integrity checksum failed when using sha512: wanted sha512-4QsFY/7vav1acsOj8xyLFuUVsJXA6m4t4u2Vyo6EJkj6p23YBSZhx80wfO8+d0lOYY0K1zgGP0Ll7rAhAi4Bjg== but got sha512-pzHCuHNoQ1dUVy9KHF28myGLiLrSn9ohtlq6ED9ZisOuoZyaLTX5JXod6dGbvccj1kQgrnwoFOCb5CA+Ajyhnw==. (53029260 bytes)
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 98492ms
11 verbose stack Error: sha512-4QsFY/7vav1acsOj8xyLFuUVsJXA6m4t4u2Vyo6EJkj6p23YBSZhx80wfO8+d0lOYY0K1zgGP0Ll7rAhAi4Bjg== integrity checksum failed when using sha512: wanted sha512-4QsFY/7vav1acsOj8xyLFuUVsJXA6m4t4u2Vyo6EJkj6p23YBSZhx80wfO8+d0lOYY0K1zgGP0Ll7rAhAi4Bjg== but got sha512-pzHCuHNoQ1dUVy9KHF28myGLiLrSn9ohtlq6ED9ZisOuoZyaLTX5JXod6dGbvccj1kQgrnwoFOCb5CA+Ajyhnw==. (53029260 bytes)
11 verbose stack     at Transform.<anonymous> (C:\nodejs\node_modules\npm\node_modules\ssri\index.js:328:19)

**To Reproduce**

1. download code of tag 2.14.4
2. install rush
3. rush install on the code.

**Expected behavior**

rush install successfully

**Screenshots**

**Desktop (please complete the applicable information):**

- OS: win10

**Comment by kabentley** [comment]
I just tried this and it worked for me. Did you try `rush install --purge`?

What versions of Node and Rush are you using?

**Comment by bvboca** [comment]
Let me have a try. 
Rush Multi-Project Build Tool version: 5.34.2
Node.js version is 12.22.1 (LTS)

**Comment by bvboca** [comment]
> I just tried this and it worked for me. Did you try `rush install --purge`?
> 
> What versions of Node and Rush are you using?

Thanks, rush install --purge works!

BTW , the sample contains some weird characters.  Are there some env I have to config?


![WechatIMG278](https://user-images.githubusercontent.com/11614025/116499458-ca968400-a8de-11eb-99cb-9667e8415944.jpeg)

**Comment by bsteinbk** [comment]
The "weird" language should only show up in dev builds. This technique allows us to verify that strings are properly set up for localization. If you want to see the original/English strings, and you are running the app locally, you can delete the `build\locales\en-PSEUDO` directory from the application so the "pseudolocalized" strings are not found.

**Comment by roluk** [comment]
@bsteinbk Deleting `en-PSEUDO` results in a failed request from frontend: `GET http://localhost:8080/locales/en-PSEUDO/App.json` Is there a way around that in dev build so that error is not logged?

**Comment by pmconne** [comment]
@bvboca if localization issues persist please open a separate issue.

**Comment by bvboca** [comment]
Thanks!
