### ISSUE TITLE
Error 400: "invalid_request invalid redirect_uri" on sign-in

### ISSUE THREAD

**Issue by roopsaini** [imodeljs/imodeljs#13]
I get the following error when I sign into the [simple-viewer-app](https://github.com/imodeljs/simple-viewer-app) after I set it up following the [instructions](https://www.youtube.com/watch?v=SPyN8w1XEAE) provided.

![redirect_1](https://user-images.githubusercontent.com/34580471/48727369-a4da0080-ebf7-11e8-8aca-c1d201fd2c37.PNG)

This happens if I use my client-id along with the default redirect-path (`imjs_test_oidc_redirect_path`) provided in the configuration.ts file.

![redirect_3](https://user-images.githubusercontent.com/34580471/48728458-9c36f980-ebfa-11e8-89b0-c73eb5ad8be6.PNG)

The reason for this is that there is currently a mismatch between the default redirect_path in the config vs. the default provided in the registration form (ie. **signin-oidc** vs. **signin-callback**).

![redirect_2](https://user-images.githubusercontent.com/34580471/48728457-9b9e6300-ebfa-11e8-804f-e88417e3132e.PNG)

The iModel.js team has been notified about this discrepancy and a fix is currently underway. As a work-around for those who have already registered using the default redirect path simply update the `imjs_test_oidc_redirect_path` as follows:

![redirect_4](https://user-images.githubusercontent.com/34580471/48728459-9c36f980-ebfa-11e8-9d4a-774c9378d3c1.PNG)

Thanks,
Roop

**Comment by roopsaini** [comment]
The default provided in the registration form and the default in the configuration file are now consistent.

**Comment by maakkoush** [comment]
Hi,

Am facing the same issue with simpleviewerapp and ninzone app. I tried the above solution but still the same issue persists. How to check the cause of the problem and resolve it? 

Thanks,
Mona
