### ISSUE TITLE
Create 3D element based on non planar closed loops with holes defined as closed loops ?

### ISSUE THREAD

**Issue by griemens** [imodeljs/imodeljs#1330]
I am using iTwinJS api to convert a CAD file to a BIM file to eventually push to an iModel on iModelHub. To check correct conversion I am using the Desktop starter application for the time being.
So far all works great boxes, cones, triangle meshes and rotationalsweeps.

Now I have a 3D element described as an outer contour and inner contours generally defining holes.
But inner contours can also intersect and the overlapping part should be rendered as a surface.

Is there something in the Geometry core API I can use for describing such elements or tesselate them ?
Typically I would use GluTess (GLU Tesselation) for such polygons.

Thank you for any tips you can provide.

**Comment by pmconne** [comment]
@EarlinLutz

**Comment by EarlinLutz** [comment]
If the loops are in a ParityRegion, the faceted parity region will be handled as you describe -- a singly-overlapped part is "in" because it is part of 3 loops (the outer and a pair of inners.)

**Comment by EarlinLutz** [comment]
(I'm wary of the "non-planar" point -- please show some snips to get a feel for that ....)

**Comment by griemens** [comment]
Thank you for the tip will try out the ParityRegion.

Related to the none planar issue.
Imagine you have a curved wall, and in the wall a curved window is added. The frame of the window is created with outer closed loop and an inner closed loop. => Although is an exceptional case I have seen this in some CAD data described as inner and outer loops. Other examples I have encountered are with curved metal grids, where the holes are created with inner loops.

But if ParityRegion can not handle such cases, will add a test if points/curves are on plane. If not fall back to different algorithm. Maybe using a library like "tess2-ts"

**Comment by EarlinLutz** [comment]
![image](https://user-images.githubusercontent.com/69321059/117155100-7bdb6500-ad8a-11eb-83ea-08f0cdc66696.png)
When you say inner loops can intersect, is it something like the outer+2Inners on the right of this png?

**Comment by griemens** [comment]
Yes correct. Where expected result in displayed view would be
![innerloop_boolean](https://user-images.githubusercontent.com/22792243/117161068-ec51a880-adc1-11eb-99f3-132af4f8a92a.jpg)

**Comment by EarlinLutz** [comment]
That is the behavior we expect from a ParityRegion.

**Comment by griemens** [comment]
Thanks for the help EarlinLutz it is working great using ParityRegion.

Code snipper I am using
```typescript
     const builder = new GeometryStreamBuilder();
     ...
     for(var surface of element.surfaces) {
         const loops: Loop[] = [];
         for(var contour of surface.contours) {
             const linestring = LineString3d.create(
                    contour.vertices.map(v => Point3d.create(v.x,v.y,v.z)));
             linestring.addClosurePoint();
             const loop = Loop.create(linestring);
             loops.push(loop);
         }
         const region = ParityRegion.createLoops(loops);
         builder.appendGeometry(region);
     }
```
Where element is of type
```typescript
const element = { 
     surfaces: {
        contours: {
            vertices: Vector3d[],
        }[],
     }[],
}
```

**Comment by griemens** [comment]
Excellent !!
Thank you for the help and example. I should be able to figure out how to build a ConvexClipSet and handle the orientation properly.
