### ISSUE TITLE
Using the Presentation API with a Sample iModel

### ISSUE THREAD

**Issue by RubberDuckDestroyer** [imodeljs/imodeljs#1360]
Hi, I'm trying to use the frontend presentation API with a sample iModel from the website. I want to get the Element ID of an element selected by the user.

Here's a screenshot of the handler I'm trying to use:
<img width="1009" alt="Screen Shot 2021-05-10 at 11 45 24 AM" src="https://user-images.githubusercontent.com/24650979/117594241-cea18c00-b191-11eb-94a7-c2d9c9a88f03.png">

And here is the configuration of the IModelApp.startup. (required before initialising Presentation)
<img width="1118" alt="Screen Shot 2021-05-10 at 1 17 30 PM" src="https://user-images.githubusercontent.com/24650979/117594420-16281800-b192-11eb-8fcd-36259608fabe.png">
 

I'm getting the following error:
`iModels.connectionError iModels.synchronizerLink`

Can someone help me out with this?

**Comment by pmconne** [comment]
What operating system and browser are you using?

**Comment by aruniverse** [comment]
Would you be able to post aarger screenshot with the rest of the code in that file?
Looks like you're importing and using the Viewer component from itwin-viewer-react. 
That component will actually call IModelApp.startup as well as Presentation.Initialize so you don't have to, so I'm curious how that CustomIModel.startup is being used. 

The error you are seeing might also be a bit misleading. Could you look at your network tab and share what the response for the openForRead call is?

**Comment by RubberDuckDestroyer** [comment]
Hi,
@pmconne OS- macOS BigSur 11.2.3. Browser: Safari & Chrome

@aruniverse That makes sense. I have attached screenshots for the full code for CustomImodel.

![Screen Shot 2021-05-13 at 9 42 50 AM](https://user-images.githubusercontent.com/24650979/118048723-c84d2300-b3d0-11eb-897b-e4129065bd86.png)
![Screen Shot 2021-05-13 at 9 43 26 AM](https://user-images.githubusercontent.com/24650979/118048726-cc794080-b3d0-11eb-971d-ddf90a1a649b.png)
![Screen Shot 2021-05-13 at 9 43 38 AM](https://user-images.githubusercontent.com/24650979/118048743-d3a04e80-b3d0-11eb-9e46-81c2eddbbd83.png)

I could not find the openForRead call in the network tab, I've attached a screenshot of what I'm seeing on the network tab as well.

![Screen Shot 2021-05-13 at 9 50 08 AM](https://user-images.githubusercontent.com/24650979/118048686-bc616100-b3d0-11eb-8f04-9b4e988b9a6c.png)

**Comment by aruniverse** [comment]
> @aruniverse That makes sense. I have attached screenshots for the full code for CustomImodel.

In your `componentDidMount` you call your `startup` which tries to do `IModelApp.startup` and `Presentation.initialize` which is unneeded, because like mentioned before, the `Viewer` component will do this for you; you just need to `initOidc`.

The `Viewer` component takes optional props for  `onIModelAppInit` and `onIModelConnected` which you can use to register your Presentation handlers.  See [docs](https://github.com/imodeljs/itwin-viewer/tree/master/packages/modules/itwin-viewer-react#optional) for more. 

> I could not find the openForRead call in the network tab, I've attached a screenshot of what I'm seeing on the network tab as well.

Are there any other requests in your network tab failing? Looks like it doesn't even get far enough to open the imodel. 
If so, take a look at the response and let us know what's failing and why.

**Comment by aruniverse** [comment]
Been over a month with no update, the steps defined above should resolve the issue. Closing issue for now, if issue persists we can reopen this.
