### ISSUE TITLE
First attempt failed

### ISSUE THREAD

**Issue by KyrieDriftwood** [imodeljs/imodeljs#14]
Managed to get it up an running on Ubuntu, but there was an error message when I tried to connect to the sample project - usinjg the sample viewer app as a test.

Recieved this from bentley:
Från: noreply@bentley.com
Datum: 2018-11-01 13:35 (GMT+01:00)
Rubrik: Your Sample IModel Project has been created

Sample IModel Project was created with Project Name: 2114_dev, and IModel Name: 2114_dev

My configuration.ts 
    imjs_test_project            : "2114_dev", // Set this to the name of the sample project
    imjs_test_imodel             : "2114_dev", // Set this to the name of the sample iModel

But the error message after pressing  Open Sample Imodel is:

Project with name "2114_dev" does not exist

**Comment by KyrieDriftwood** [comment]
Updated Title

**Comment by LabyrinthTechnology** [comment]
I recommend to start with a check whether you have access to the model. See #3 for an issue that may happen and how to check sample model accessibility.

**Comment by roopsaini** [comment]
Hi @KyrieDriftwood,

Were you able to view the project on the [CONNECT](https://connect.bentley.com/) portal as @LabyrinthTechnology suggested?

**Comment by KyrieDriftwood** [comment]
![image](https://user-images.githubusercontent.com/4728106/49038073-2adbe580-f1bc-11e8-8ed3-96a7819bdf09.png)

There is no project that I can find using the search tool. 

I have created a new project, maybe it will work better

**Comment by LabyrinthTechnology** [comment]
> I have created a new project, maybe it will work better

It has be created by Bentley for you and example data put in.

**Comment by roopsaini** [comment]
I am investigating this on our end. Do you see anything at all under "My Projects"?

**Comment by KyrieDriftwood** [comment]
Hello, Yes it is the same email. The same used in mine and roopsainis earlier conversation via email

have now received an email which gave me an userID (which I didn't get in the first E-mail). I now have the following configuration.ts
[configuration.ts.txt](https://github.com/imodeljs/imodeljs/files/2626582/configuration.ts.txt)


Now - after signing in - I could grant permission to the project 2114_dev. However, still the same error message as before "Project with name "2114_dev" does not exist". 

Under my CONNECT service page I can see other project that I have created, but not this one. Are there certain privileges that I need to have?

**Comment by roopsaini** [comment]
Offered a suggestion via email. Still waiting to hear back from @KyrieDriftwood. Closing the issue for now, please reopen if the issue persisted.
