### ISSUE TITLE
Schema update in iModel

### ISSUE THREAD

**Issue by ashish-srivastava-dev** [imodeljs/imodeljs#1479]
Is there any available tool or utility, using which we can upgrade domain schema to an iModel? Or Please point me to some sample code which upgrades schema to an iModel?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Schemas-and-Elements-in-TypeScript---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/backend/schemasandelementsintypescript/

**Comment by pmconne** [comment]
@scsewall?

**Comment by scsewall** [comment]
You can use the [importSchemas](https://www.itwinjs.org/reference/imodeljs-backend/imodels/imodeldb/importschemas/?term=imports) method to import new schemas and upgrade existing schemas. Note that those changes should be committed and pushed separately (not mixed in with actual element data changes).
