### ISSUE TITLE
Connection from localhost to iModel is flacky

### ISSUE THREAD

**Issue by eap23** [imodeljs/imodeljs#1540]
**Describe the bug**
Successfully establishing a connection to the _iModel_ from the online course https://itwinaccreditation.matrixlms.com/visitor_catalog_class/show/638695 is flacky. When not successful I am shown the error in the screenshot below.

**To Reproduce**

1. Running the _React_ app from the online course using `npm run start`
2. New browser window/tab opens using `http://localhost:3000`
3. See error from screenshot attached below

**Expected behavior**
Successfull connection to sample _iModel_ as shown in screenshot below

**Screenshots**
![210601Firefox_iTwin_ReactSample_iModelConnectionError](https://user-images.githubusercontent.com/26528531/120288311-5b86c380-c2c0-11eb-9f21-9d2c47080100.png)
![210528Firefox_iTwin_ReactSample_iModel](https://user-images.githubusercontent.com/26528531/120289230-5d04bb80-c2c1-11eb-89c4-35031a9dcd81.png)

**Desktop (please complete the applicable information):**

- OS: Windows 10 Version 1909 (Build 18363.1556)
- Browser: Firefox
- Version: 88.0.1 (64-Bit)
- iTwin.js Version `^2.16.1` (accord.  `package.json`)

**Comment by pmconne** [comment]
Thanks. If you see any network errors when this exception occurs, could you share them please?
@williamkbentley @calebmshafer is this another case of needing to update RBAC permissions?
https://github.com/imodeljs/imodeljs/discussions/1130
https://github.com/imodeljs/imodeljs/issues/1360

**Comment by eap23** [comment]
This is the content of _Firefox_ console after the error screen appears:

> [HMR] Waiting for update signal from WDS... log.js:24
> Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:24994
> ./node_modules/@bentley/ui-ninezone/lib/ui-ninezone/footer/Separator.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--7-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-5-4!./node_modules/@bentley/ui-ninezone/lib/ui-ninezone/footer/Separator.scss)
> Warning
> 
> (28:3) Replace fill-available to stretch, because spec had been changed webpackHotDevClient.js:138
> Das Components-Objekt sollte nicht mehr verwendet werden. Es wird bald entfernt. localhost:3000
> iModel.js initialized Initializer.ts:350
> Error opening the iModel connection: Error: Too Many Requests IModelService.ts:75
> Uncaught Error: iModels.connectionError iModels.synchronizerLink
>     throwFatalError useErrorManager.ts:74
>     node_modules 0.chunk.js:265785
> useErrorManager.ts:74
> The above error occurred in one of your React components:
>     in Unknown (created by IModelLoader)
>     in IModelLoader (created by Viewer)
>     in ErrorBoundary (created by Viewer)
>     in Viewer (at App.tsx:109)
>     in div (at App.tsx:99)
>     in App (at src/index.tsx:9)
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. index.js:1
> react-i18next:: You will need pass in an i18next instance by using initReactI18next utils.js:11
> Das Components-Objekt sollte nicht mehr verwendet werden. Es wird bald entfernt. blank

_Fiddler_ reports 429 returning response body:
```
{
  "statusCode": 429,
  "message": "Rate limit is exceeded. Try again in 27 seconds."
}
```

**Comment by pmconne** [comment]
> > Error opening the iModel connection: Error: Too Many Requests IModelService.ts:75

Thanks. @laurynasr can you please provide a solution for this rate limiting?

**Comment by laurynasr** [comment]
This should be fixed now

**Comment by eap23** [comment]
Seems working now, thanks!
