### ISSUE TITLE
Potentially outdated header and sidebar.

### ISSUE THREAD

**Issue by donvi-bz** [imodeljs/imodeljs#1579]
Sorry if this is a non-issue, I really can't tell if this is on purpose or not, but:
Unlike most of the other pages, the header on this one says iModel.js, and in the header the versions are 2.3.0 and 1.14.0 (whereas it looks like the current version if iTwin.js is up to 2.16). The sidebar has less links than the side bars on all the pages with the iTwin.js logo, but the links on this sidebar link to pages with the iTwin.js logo. Also, the "edit this page" link brings up a 404 page not found on github.
If there is a distinction between iModel.js and iTwin.js and I'm being stupid, sorry, but it looks like this page just has an outdated header and sidebar.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Bentley-iTwin-Service---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/itwinservice/

**Comment by pmconne** [comment]
@williamkbentley

**Comment by williamkbentley** [comment]
Looks like the [page was deleted](https://github.com/imodeljs/imodeljs/tree/master/docs/learning%2FiTwinService.md) but is still in our CDN. @BaoTon an I will get it purged. Thanks for bringing this to our attention.

**Comment by donvi-bz** [comment]
Is the information here still correct?

**Comment by williamkbentley** [comment]
Yes, it has just moved: https://www.itwinjs.org/learning/clients/itwinservice/

**Comment by donvi-bz** [comment]
Alright, thank you!
