### ISSUE TITLE
Getting error in desktop-starter 

### ISSUE THREAD

**Issue by ashishagarwal7** [imodeljs/imodeljs#1586]
(node:11780) UnhandledPromiseRejectionWarning: Error: Assert: No Client ID provided.
I am getting this error whether i am providing client id or not.

* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Developing-a-desktop-viewer---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/develop-desktop-viewer/

**Comment by williamkbentley** [comment]
If you set `const clientId = "native-XXXXXXXXXXXXXXXXXXX";`, you can safely remove the `assert`. I [updated this tutorial](https://github.com/imodeljs/imodeljs/pull/1575/files) last week, so expect this documentation to be updated shortly.

**Comment by calebmshafer** [comment]
going to close this as fixed. Please re-open or open a new one if you run into issues.
