### ISSUE TITLE
Clarification on where the iModel copy comes from

### ISSUE THREAD

**Issue by donvi-bz** [imodeljs/imodeljs#1673]
One question, one possible place for clarification regarding this line:
>  iTwin.js applications always work on a copy of an iModel in a briefcase, obtained from iModelHub, and process it locally, making them infinitely scalable.

Q: How does the briefcase relate to an iModel Snapshot?

C: I'm pretty sure this copy can *also* be produces completely without the iModelHub, from one of my last questions I learned that the iTwin Snapshot tool can make a snapshot usable by iTwin. Should this statement be clarified to say that the copy can be obtained either from the iModelHub or locally from a snapshot made with the iTwin Snapshot tool?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Documentation-Overview---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/

**Comment by kabentley** [comment]
you are correct, that sentence should say: "..always work on a copy of an iModel, in a briefcase obtained from iModelHub, or a local snapshot iModel..."

The slight difference from your wording is that you can obtain a snapshot by downloading a readonly "checkpoint" iModel from iModelHub for archival or simply offline viewing . That's important so you're not locked in to always having your data in iModelHub, as is the case with most cloud-only "BIM viewer" services.

I will update the documentation.

HTH,
Keith
