### ISSUE TITLE
Use "Synchronized", in lieu of "Aligned", as heading

### ISSUE THREAD

**Issue by rssahai** [imodeljs/imodeljs#1679]
The title "Aligned" isn't supported by the content describing it. "Synchronized", being what iModel Connectors do, is the concept closest to what the content is describing.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Federated-Digital-Twins-for-Infrastructure-Engineering---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/bis/intro/federated-digital-twins/

**Comment by kabentley** [comment]
I disagree.  This section of the BIS documentation is about "Alignment," which is a very key part of the job of an iModel Connector. That is, connectors don't simply map source data "as is", leaving an jumbled mix of data types in an iModel. Instead, they attempt to "map" data into the BIS taxonomy so what can be in common is in common, even across disparate source applications.

You are right though, synchronization (detecting change, vs. wholesale import/export) is a key part of what makes a "connector" a connector. That should be explained elsewhere though.

**Comment by rssahai** [comment]
Your insight about alignment isn't clear in the section as written. Inserting a second sentence in the section will, I believe, make it real: "For the digital replica to be cohesive, the source data from disparate applications must be mapped with a standard taxonomy so the data aligns into a meaningful model."

**Comment by kabentley** [comment]
see if you like [this](https://github.com/imodeljs/imodeljs/pull/1692) better

**Comment by rssahai** [comment]
This works. The meaning and value of alignment is now explicit.
