### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by YouYue123** [imodeljs/imodeljs#17]
Hi,

Amazing to see this from Bentley Systems. It really helps a lot with a stable production ready 1.0 release.

Do you have any roadmap and plan to a production ready 1.0?

Thanks

**Comment by kabentley** [comment]
We expect to release version 1.0 by the end of 1Q19.

HTH,
Keith

**Comment by YouYue123** [comment]
Nice . Good to hear that. Where can I find the detailed roadmap?

**Comment by LabyrinthTechnology** [comment]
> Where can I find the detailed roadmap?

This is _open source_ project, where the development consists from cooperation of more subjects and merge requests, so I guess there is nothing like _detail roadmap_.

BTW Why the detail roadmap is important for you?
