### ISSUE TITLE
Mesh model freezing issue in imodeljs (.TileCache size issue)

### ISSUE THREAD

**Issue by namsancow** [imodeljs/imodeljs#170]
* I have already registered this issue for "Discussions"

MicroStation has many element type such as surface, solid, cell, shape, and mesh etc. 

For surface, solid, cell, shape model, the published bim file works quickly in imodeljs. 
However for mesh model, the published bim file works very slowly. 
The imported mesh model from fbx, obj, 3ds file also works very slowly.

When bim file is published, the .Tiles and TileCache files are generated together. 
.Tiles and TileCache files used with .bim files in imodeljs when zooming and rotating.

For surface, solid, cell, shape model, .Tiles and TileCache files has no problem. 
However, for mesh model, the imodeljs is continually freezing. 

If the .TileCache file size is increased, can this freezing issue be solved?
Is there any method for increasing .TileCache file size?

**Comment by pmconne** [comment]
What application are you using to view the iModel?
The .tilecache file is neither produced nor used by iModel.js applications and its size certainly should not be changing as you navigate the model within an iModel.js application.
The .tiles file is populated with tiles as they are generated.
If you can provide more information about your model (or even the .bim itself) we will have a much better chance of diagnosing the problem.

**Comment by namsancow** [comment]
> What application are you using to view the iModel?
> The .tilecache file is neither produced nor used by iModel.js applications and its size certainly should not be changing as you navigate the model within an iModel.js application.
> The .tiles file is populated with tiles as they are generated.
> If you can provide more information about your model (or even the .bim itself) we will have a much better chance of diagnosing the problem.

Thank you for your kind answer.
I was wrong about the need for *.Tilecache file.
When I opened the *.bim file in imodeljs, I noticed that the files of *.Tile, *.HeirchyCache.db, 
and *.HeirchyCache.db were automatically created.
Without the file *.TileCache, there was no problem opening the file *.bim in imodeljs.

If it's not a TileCache issue, I wonder if there's another way to quickly process the mesh model in imodeljs.
