### ISSUE TITLE
Location coordinates for any place clicked in viewer

### ISSUE THREAD

**Issue by ashish-srivastava-dev** [imodeljs/imodeljs#1792]
How can I get location coordinates for any location clicked in viewer? I want the location in JavaScript code.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: iTwin.js-API-Reference-Documentation---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/

**Comment by pmconne** [comment]
Have a look at the [MeasureLocationTool](https://github.com/imodeljs/imodeljs/blob/c889d837b9f034d28da4e99b93d8a05891cdfe72/core/frontend/src/tools/MeasureTool.ts#L669).

**Comment by pmconne** [comment]
Closing because this is not an issue. Please use the [discussions page](https://github.com/imodeljs/imodeljs/discussions) for asking questions.

**Comment by ashish-srivastava-dev** [comment]
Hi Paul,

Can you point me to some code samples which use this tool to capture location coordinates?

Thanks.

Best Regards,
Ashish Srivastava

**Comment by pmconne** [comment]
No, I can't. An app installs the tool, the user clicks on locations, and the tool reports their coordinates. Look at the implementation of the tool linked above to see how it works.
