### ISSUE TITLE
I need to open my local .iModel file via iModelDb.openStandalone can you please guide us

### ISSUE THREAD

**Issue by rachitsakhidas** [imodeljs/imodeljs#19]
I have a question regarding iModel.js (Front-End Application)

I plan to open my local iModel files via iModelDb.openStandalone method

Is there support for markups / annotations within imodeljs? If yes, what is the best way to configurable / enable this functionality?

Thanks & Regards
Rachit V. Sakhidas

**Comment by roopsaini** [comment]
Hi @rachitsakhidas,

Just a heads up: the openStandalone method will soon be deprecated and replaced by the [snapshot iModel](https://github.com/imodeljs/imodeljs/issues/4#issuecomment-435976612). 

We will be releasing some markup / annotation support within the next few weeks.
