### ISSUE TITLE
Modification dates

### ISSUE THREAD

**Issue by bradjamesgrant** [imodeljs/imodeljs#1985]
I'm looking to know when a model from an external source (Projectwise) was last consumed in an iModel. Would the command "select * FROM Bis.ExternalSourceAspect si JOIN bis.Model e ON si.Scope.Id = e.ECInstanceId Where si.Identifier LIKE 'pw%'" give the correct link between a projectwise file location and a model and their respective details? Or is there a better method?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: ExternalSourceAspect---imodeljs-backend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/imodeljs-backend/elementaspects/externalsourceaspect/

**Comment by swwilson-bsi** [comment]
select LastMod from bis.repositorylink where codevalue like 'pw%'

LastMod is juliandays, UTC.

If you are doing this programmatically in iModel.js and you want to get the timestamp back as a formatted string, you can do this:

select cast(LastMod as timestamp) from bis.repositorylink where codevalue like 'pw%'

**Comment by pmconne** [comment]
Closing as question has been answered.
