### ISSUE TITLE
Test issue, please ignore

### ISSUE THREAD

**Issue by williamkbentley** [imodeljs/imodeljs#20]
Please ignore
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: IModelJsFsStats---imodeljs-backend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/reference/imodeljs-backend/portability/imodeljsfsstats/

**Comment by williamkbentley** [comment]
Closing test issue

**Comment by BaoTon** [comment]
Adding test comment.
