### ISSUE TITLE
Display data using tooltips upon hover

### ISSUE THREAD

**Issue by kiranshetty07061999** [imodeljs/imodeljs#2039]
<img width="1440" alt="Screenshot 2021-08-11 at 5 40 39 PM" src="https://user-images.githubusercontent.com/88778907/129026451-7f9b8f4a-d1a1-4359-a0f2-8a0d68127fa1.png">

Hey,
 I want to display data on the components of the imodel using tooltip hover. I have got the codes from this link below
https://github.com/imodeljs/imodeljs/blob/master/ui/ninezone/src/ui-ninezone/popup/Tooltip.tsx#L37

I am getting data from iconsole. How do i map it on the model?

I have attatched the screenshot of the model above

Please help
 
I

**Comment by pmconne** [comment]
When you mouse over an element in a viewport, a tooltip showing some information about that element is displayed.
Are you asking to replace or augment the information displayed in that tooltip? If not, please clarify your question.
If so, please clarify what "data from iconsole" means and how it relates to the contents of the iModel.

**Comment by kiranshetty07061999** [comment]
Nope..I am not able to display the tooltip upon hover at all...

**Comment by pmconne** [comment]
If you don't see a default tooltip when mousing over an element in the viewport while the browser window has focus, check console for any errors. You should always see *something*.
Please supply the information requested in previous reply.

**Comment by DanEastBentley** [comment]
Before calling the `IModelApp.startup` function, are you setting the `opts.iModelApp.notifications` variable similar to the following:

```ts
import { AppNotificationManager } from "@bentley/ui-framework";
. . .
  const opts: WebViewerAppOpts & NativeAppOpts = {
    iModelApp: {
 . . .
      notifications: new AppNotificationManager(),
 . . .
    },
 . . .
  };

  // Start the app.
  await SampleAppIModelApp.startup(opts);
```

The implementation of `NotificationManager.openToolTip` or `._showToolTip` puts the tooltip on the screen.

**Comment by kiranshetty07061999** [comment]
> If you don't see a default tooltip when mousing over an element in the viewport while the browser window has focus, check console for any errors. You should always see _something_. Does the element "flash" (change color or brighten in color)?
> Please supply the information requested in previous reply.



<img width="1440" alt="Screenshot 2021-08-11 at 8 42 29 PM" src="https://user-images.githubusercontent.com/88778907/129055913-b33d24b6-a575-497c-aa50-27f310a55158.png">
As u can see in the above screenshot...by default, I am able to see the tooltip on that component....but i am not able to see the same for all the components out there.....I am attaching another screenshot to demonstrate the same.
<img width="1440" alt="Screenshot 2021-08-11 at 8 50 41 PM" src="https://user-images.githubusercontent.com/88778907/129056904-45fffae7-903b-44c2-9d2a-6f0bc5bcc9f9.png">


My requirement is to get the data onto the component on hovering the cursor on to them. The data from iconsole means the data from the biscore schemas which was synchronised by the itwin synchroniser

**Comment by kiranshetty07061999** [comment]
> Before calling the `IModelApp.startup` function, are you setting the `opts.iModelApp.notifications` variable similar to the following:
> 
> ```ts
> import { AppNotificationManager } from "@bentley/ui-framework";
> . . .
>   const opts: WebViewerAppOpts & NativeAppOpts = {
>     iModelApp: {
>  . . .
>       notifications: new AppNotificationManager(),
>  . . .
>     },
>  . . .
>   };
> 
>   // Start the app.
>   await SampleAppIModelApp.startup(opts);
> ```
> 
> The implementation of `NotificationManager.openToolTip` or `._showToolTip` puts the tooltip on the screen.

I havent used that

> Before calling the `IModelApp.startup` function, are you setting the `opts.iModelApp.notifications` variable similar to the following:
> 
> ```ts
> import { AppNotificationManager } from "@bentley/ui-framework";
> . . .
>   const opts: WebViewerAppOpts & NativeAppOpts = {
>     iModelApp: {
>  . . .
>       notifications: new AppNotificationManager(),
>  . . .
>     },
>  . . .
>   };
> 
>   // Start the app.
>   await SampleAppIModelApp.startup(opts);
> ```
> 
> The implementation of `NotificationManager.openToolTip` or `._showToolTip` puts the tooltip on the screen

havent tried it...let me just check it out .....👍🏻

**Comment by kiranshetty07061999** [comment]
I have used the following code to get tooltip.....Can u help me in detail on the implementation of tooltips to get the data of the individual components on hover


/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/
/** @packageDocumentation
 * @module Popup
 */
import  "../decorators/SmartDeviceDecorator"
 import "./Tooltip.scss";
 import classnames from "classnames";
 import * as React from "react";
 import { CommonProps, Point, PointProps, Rectangle, RectangleProps, Size, SizeProps } from "@bentley/ui-core";
//  import { CssProperties } from "./css";
 
 /** Properties of [[Tooltip]] component.
  * @beta
  */
 export interface TooltipProps extends CommonProps {
   /** Tooltip content. */
   children?: React.ReactNode;
   /** Tooltip icon. */
   icon?: React.ReactNode;
   /** Function called when the bounds of the tooltip changes. */
   onSizeChanged?: (size: SizeProps) => void;
   /** Position of the tooltip. */
   position: PointProps;
 }
 
 /** Default properties of [[Tooltip]] component.
  * @beta
  */
 export type TooltipDefaultProps = Pick<TooltipProps, "position">;
 
 /** Positionable tooltip component.
  * @beta
  */
 export class Tooltip extends React.PureComponent<TooltipProps> {
   public static readonly defaultProps: TooltipDefaultProps = {
     position: {
       x: 50,
       y: 60,
     },
   };
 
   private _lastSize = new Size();
   private _tooltip = React.createRef<HTMLDivElement>();
 
   public override render() {
     const className = classnames(
       "nz-popup-tooltip",
       this.props.className);
 
    //  const style: React.CSSProperties = {
    //    ...this.props.style,
    //    ...CssProperties.fromPosition(this.props.position),
    //  };
 
     return (
       <div
         className={className}
         ref={this._tooltip}
        //  style={style}
       >
         {this.props.icon !== undefined ?
           <div>
             {this.props.icon}
           </div> : undefined}
         <div className="nz-content">
           {this.props.children}
         </div>
       </div>
     );
   }
 
   public override componentDidMount() {
     this.onSizeChanged();
   }
 
   public override componentDidUpdate(): void {
     this.onSizeChanged();
   }
 
   private onSizeChanged() {
     const tooltip = this._tooltip.current;
     if (!tooltip)
       return;
 
     const rect = tooltip.getBoundingClientRect();
     const size = {
       height: rect.height,
       width: rect.width,
     };
 
     if (this._lastSize.equals(size))
       return;
 
     this._lastSize = Size.create(size);
     this.props.onSizeChanged && this.props.onSizeChanged(size);
   }
 }
 
 /** Function to apply offset and contain tooltip bounds in container.
  * @internal
  */
 export const offsetAndContainInContainer = (tooltipBounds: RectangleProps, containerSize: SizeProps, offset: PointProps = new Point(20, 20)): Point => {
   let newBounds = Rectangle.create(tooltipBounds).offset(offset);
   const containerBounds = Rectangle.createFromSize(containerSize);
   if (containerBounds.contains(newBounds))
     return newBounds.topLeft();
 
   newBounds = newBounds.containIn(containerBounds);
   return newBounds.topLeft();
 };

**Comment by kiranshetty07061999** [comment]
I have  tried using the code from the below link

https://www.itwinjs.org/sample-showcase/?group=Viewer+Features&sample=tooltip-customize-sample&gallery=false&imodel=Metrostation+Sample

But i am not able to find the following packages in npm

@itwinjs-sandbox/hooks/useSampleWidge   and  @itwinjs-sandbox

Any idea how to access them?

**Comment by Ellord207** [comment]
This package is intended just to support the samples you linked to, and not for users consumption.  What "useSampleWidget" does is create the "Sample Information" panel in the sample.

For more information about using the showcase samples in your own app, we have a tutorial for it.
https://developer.bentley.com/tutorials/adding-showcase-widgets-to-your-itwin-viewer/
