### ISSUE TITLE
Some questions regarding iModel and iModel.js

### ISSUE THREAD

**Issue by sveale** [imodeljs/imodeljs#21]
Hi,

I have some questions regarding iModel and iModel.js that I hope someone here can answer. If this is the wrong place for one or more of the questions below I would appreciate feedback on that as well.

 1. I understand the C++ SDKs for iModel are only for iModel 1.x and will no longer be developed, is that correct?
 2. Are there any plans for publishing a C++/C library for reading iModel 2.x? For a lot of existing applications, including SW products that I am involved with, it will be quite difficult to integrate with iModel.js without doing a complete rewrite or making a converter using iModel.js and Electron.
 3. We currently use a library from ODA (previously called Teigha) to import CAD files (e.g. DGN, DWG etc.) into our software. As Bentley is founding/corporate member of the ODA, are there any concrete plans and timeline to add support for iModel in ODA?
 4. Regarding the iModel.js native module license (https://github.com/imodeljs/imodeljs/blob/master/core/backend/src/imodeljs-native-LICENSE.md) are there any restrictions on including this in a commercial product?

**Comment by kabentley** [comment]
1) yes.
2) the iModel.js library is the only public api. To interface to them from C++, you can make a multi-process application that communicates via pipes and JSON. We do that for our translators. That avoids most of the nightmares with C++ libraries around versions, compiler options, etc.
3) as an open source library, ODA is free to use/modify iModel.js. We'd love to help them do that, though we've only had introductory discussions with them about that.
4) we hope many people will incorporate iModel.js into commercial applications. The requirement is that to connect their iModel to a timeline, your **end-user** will need an iTwin subscription.  That's Bentley's commercial motivation for creating iModel.js. Under that scenario, there is no commercial or contractual relationship between you (the application author) and Bentley.
