### ISSUE TITLE
Always getting an invalid_client on getAccessToken()

### ISSUE THREAD

**Issue by BaoTon** [imodeljs/imodeljs#2104]
Steps to repro:

1. Register a new service using https://developer.bentley.com/register/
2. Construct new AgentAuthorizationClient() with passed in clientId/secret/scopes
3. Call .getAccessToken(clientRequestContext)
3. Returns Authorization error: invalid_client (Invalid client or client credentials.)

It seems I can still retrieve older access tokens from older agents/services, but any newly created agents/services always fail. Am I missing something?

* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: AgentAuthorizationClient---backend-itwin-client-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/backend-itwin-client/authentication/agentauthorizationclient/

**Comment by calebmshafer** [comment]
@BaoTon there is scheduled maintenance ongoing with our Identify Provider (IMS) and all clients will not be persisted correctly with it until the maintenance is completed.  I believe, I'll need to confirm, that all client registrations made during the scheduled outage will be cached and then applied once the maintenance is completed. So once maintenance is over you should be able to use the registered client.

Please check here for scheduled maintenance and when the IMS will be back up and fully running, https://status.bentley.com.

If the client is still not available by tomorrow, please reach back out and we will look into what may have gone wrong.

**Comment by BaoTon** [comment]
Thanks Caleb, looks like I got stuck in between maintenance. Cheers.
