### ISSUE TITLE
[ui-core] `resizeObserver.current` is null when closing desktop app window

### ISSUE THREAD

**Issue by MichaelBelousov** [imodeljs/imodeljs#2119]
**Describe the bug**
In my iTwin electron application, when I hit the close-window button at the top-right of the window on windows, I get a `TypeError: Cannot read property 'unobserve' of null`, in the `useRefEffect` clean up callback in `useResizeObserver.tsx`.
This can be seen in the last couple of seconds before the window fully dies, or in some cases seems to prevent the window from closing and closing must be attempted again.

The line `instance && resizeObserver.current!.unobserve(instance)` has a non-null assertion which fails here, on several view elements such as the following:
![electron_dO6fYMYJU7](https://user-images.githubusercontent.com/16315257/130510802-dbdba94f-c79c-4434-a752-22313e876df1.png)

**To Reproduce**

I have an example private application that reproduces this, which I can share a reproduction from if reached out to.

**Expected behavior**
To not have an error thrown when the close window button is pressed.

**Desktop (please complete the applicable information):**

- OS: Windows 10
- Browser: Electron
- Version: Electron@11.1
- iTwin.js Version [e.g. 2.19.6]

**Comment by bsteinbk** [comment]
@MichaelBelousov This was addressed in https://github.com/imodeljs/imodeljs/pull/2000 and can be backported to 2.19 if critical.

**Comment by MichaelBelousov** [comment]
I wouldn't consider it critical. But it will be user-facing on our end before updating to 3.0 is possible.

**Comment by MichaelBelousov** [comment]
More specifically, we use itwin-viewer which has an error boundary that will show this type error to the user, and which, afaik, we don't have control over the error display.
