### ISSUE TITLE
Cannot find module './technical-preview-badge.svg?sprite' from 'node_modules/@bentley/ui-core/lib/ui-core/badge/BetaBadge.js'

### ISSUE THREAD

**Issue by SunilPrasad** [imodeljs/imodeljs#2132]
While writing unit test I am getting this error . I am using following packages 

"@bentley/ui-abstract": "^2.18.4",
"@bentley/ui-components": "^2.19.6",
"@bentley/ui-core": "^2.19.6",

**Comment by bsteinbk** [comment]
See [setup-test.js](https://github.com/imodeljs/imodeljs/blob/09672c57d6ba4b0880411d674aedc059653ab5f8/ui/scripts/setup-tests.js#L45-L46) entry that is used to avoid this issue in unit tests.
