### ISSUE TITLE
Unsuccessful HTTP response

### ISSUE THREAD

**Issue by kiranshetty07061999** [imodeljs/imodeljs#2162]
Hey,
     I am getting an "Unsuccessful HTTP"  response on the browser when I run my model in the VS code. I have added my imodel onto the imodel hub. I have also added the necessary Authorization Client Settings and Test ids in the env file. I have attached the screenshot of the same for better understanding. Any idea on how to resolve this?

<img width="1440" alt="Screenshot 2021-08-30 at 9 51 03 AM" src="https://user-images.githubusercontent.com/88778907/131285170-a16b5c00-b54f-4fe4-b79b-5ce8d4938e70.png">

**Comment by aruniverse** [comment]
What version of iTwin.js are you using?
What's the version of itwin/web-viewer-react you are using?

You are getting a 401, unauthorized, error. Take a look at that failing request. I suspect you are using the wrong auth issuer. Please take a look at: https://github.com/imodeljs/imodeljs/discussions/2158. If that doesn't solve your problem, please share the exact error message you are getting from that 401.

**Comment by kiranshetty07061999** [comment]
Thanks @aruniverse. It was because of the wrong auth user. Got it fixed!
