### ISSUE TITLE
 iModel Schema Explorer does not have elements labeled as Smart devices.

### ISSUE THREAD

**Issue by JiriJa** [imodeljs/imodeljs#2188]
Hello iTwin.js team,

Please can I ask You? … I have done Accredited iTwin developer course via YouTube channel. So now I would like to test some next modifications, but sample Smart House from Bentley server via iModel Schema Explorer does not have elements labeled as Smart devices. ☹
Please can send me Your original DGN file with this elements? I would like to use iTwin Synchronizer to push it as my local file.

Thank You very much.

Best regards Jiri.

* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Developing-a-Web-Viewer---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/develop-web-viewer/

**Comment by BaoTon** [comment]
Hi Jiri,

If you're talking about the House Model from https://www.itwinjs.org/sample-showcase/ vs. the one used on the accreditation program, these are two separate DGNs.

The accreditation DGN can be found here: https://github.com/iTwin/Course_1-Smart-House-Sample/blob/main/House_Model.dgn but the House Model available on our showcase/sandbox is currently unavailable for public use.

Thanks,
-Bao

**Comment by JiriJa** [comment]
Thanks, Jiri.
