### ISSUE TITLE
Get information of  the components in a model upon click

### ISSUE THREAD

**Issue by kiranshetty07061999** [imodeljs/imodeljs#2191]
Hi there,

I want to display the information of individual components on the model upon clicking them. Any idea on how to achieve this?

Note:- I have planned to implement this by recording the ecinstanceid of the components upon click and then display other information related to it based on the selection....but i am not sure how to record the ecinstanceid of the components on click...

**Comment by aruniverse** [comment]
Just want to confirm that this is a duplicate issue of https://github.com/imodeljs/imodeljs/issues/2235, is that correct?

**Comment by kiranshetty07061999** [comment]
Yup....
