### ISSUE TITLE
Bis Documentation?

### ISSUE THREAD

**Issue by childish23** [imodeljs/imodeljs#22]
Hi, I am new to iModel 2.0. I am trying understand the concepts of BIS, and its role in interdisciplinary infrastructure modeling. Is there any documentation on the subject?

**Comment by LabyrinthTechnology** [comment]
Hi,

> Is there any documentation on the subject?

There is a [description of BIS](https://imodeljs.github.io/iModelJs-docs-output/bis/) available at gtihub.io (which is generated from [iModeJS-docs-output](https://github.com/imodeljs/iModelJs-docs-output) repo).

The documentation is "technical oriented", but based on BIS features and specs knowledge, I guess you should be able to position better BIS role in the discussed topic.

With regards,

  Jan

**Comment by childish23** [comment]
@LabyrinthTechnology This is very helpful. Thanks!
