### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by benjamin-lindsey** [imodeljs/imodeljs#2221]
This tutorial did not work for me on Linux. Instead I followed the instructions on the npmjs website for @itwin/desktop-viewer-react. I would recommend adding the npm or yarn command for installation of the @itwin/desktop-viewer-react package before the npx command as that's what made the difference on my system. Not sure if this is an issue for other platforms like Windows.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Developing-a-Desktop-Viewer---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/develop-desktop-viewer/

**Comment by aruniverse** [comment]
Could you share the error you saw when you used the npx command?

I recommend uninstalling create-react-app, and reinstalling it again, then trying the npx command again.

```sh
npm uninstall -g create-react-app
npm install -g create-react-app
```

**Comment by benjamin-lindsey** [comment]
@aruniverse - Just tested your suggestion on a new VM. It worked! And now I can't get it to break again, even after uninstalling all global node packages and creating a new app. I'll take some time later to set up a fresh VM and send you the errors. Many thanks for the help.

**Comment by aruniverse** [comment]
Glad that worked, i'm guessing the real issue you saw stems from here, https://github.com/facebook/create-react-app/issues/10132#issue-749030789
