### ISSUE TITLE
Provisioning schema in iModel

### ISSUE THREAD

**Issue by ashish-srivastava-dev** [imodeljs/imodeljs#2226]
How do I know whether iModel is provisioned with a particular domain schema from frontend code? If schema is already loaded then I don't want to upload it again. The app has a UI control which would enable schema upload (happening in backend) or not enable.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: SchemaState---imodeljs-common-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/imodeljs-common/imodels/schemastate/

**Comment by pmconne** [comment]
Please use the [discussions](https://github.com/imodeljs/imodeljs/discussions) page for asking questions; the issues page is for reporting bugs.
