### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ELymar** [imodeljs/imodeljs#23]
"ElementAspect instances are owned a single Element" should be "ElementAspect instances are owned by a single Element"
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Fabric-of-the-Universe---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/bis/intro/fabric-of-the-universe/

**Comment by roopsaini** [comment]
@ELymar Thanks for notifying us. I will inform the docs team.
