### ISSUE TITLE
"Unhandled Rejection (Bad Model): ViewCreator3d.createDefaultView: no 3D models found in iModel

### ISSUE THREAD

**Issue by Malashree99** [imodeljs/imodeljs#2370]
**Describe the bug**
"Unhandled Rejection (Bad Model): ViewCreator3d.createDefaultView: no 3D models found in iModel"

**Additional context**
I'm getting an about mentioned error but I can see my modal in IModalweb
![Screenshot (3)](https://user-images.githubusercontent.com/77370444/135216380-16b7fb34-b903-452d-89c0-a0b0020d1189.png)

**Comment by aruniverse** [comment]
Please provide more details like what version of @itwin/web-viewer-react and iTwin.js you are using

**Comment by pmconne** [comment]
The error is telling you the problem: your iModel contains no 3d models. Specifically, the following query returns zero results:
`SELECT ECInstanceId FROM Bis.GeometricModel3D WHERE IsPrivate = false AND IsTemplate = false AND isNotSpatiallyLocated = false`
@roopksaini, it should probably not produce an error in such a case; instead it should return a view that displays no models, with its extents based on the iModel's project extents.
@Malashree99, consider using [SpatialViewState.createBlank](https://www.itwinjs.org/reference/imodeljs-frontend/views/spatialviewstate/createblankstatic/) as a workaround for now.
