### ISSUE TITLE
Pass multiple widgets in the viewer 

### ISSUE THREAD

**Issue by kiranshetty07061999** [imodeljs/imodeljs#2432]
Hey, I have two widget components chartProviders and uiProviders . How do i pass both the widgets to uiProviders prop simultaneously? 

 const chartProviders = [new SmartDeviceUiItemsProvider()]
  const uiProviders = [new  SelectionOfComponentsWidget()];

return (
   
        <Viewer
          contextId={contextId}
          iModelId={iModelId}
          authConfig={{ config: authConfig }}
          onIModelAppInit={onIModelAppInit}
          viewCreatorOptions={{ viewportConfigurer: viewConfiguration }}
          onIModelConnected = {onIModelConnected}
          uiProviders={uiProviders}
        />
    </div>
  );};

**Comment by pmconne** [comment]
I'd expect you do so like:
```
  uiProviders={[chartProviders, uiProviders]}
```

Please use the [discussions page](https://github.com/imodeljs/imodeljs/discussions) for questions.

**Comment by aruniverse** [comment]
> I'd expect you do so like:
> 
> ```
> 
>   uiProviders={[chartProviders, uiProviders]}
> 
> ```
Paul's got the right idea here. 

But next time please take a look at the documentation for the viewer, where it states the Viewer has a prop, uiProviders, which accepts an array of UiItemsProviders. 

So Paul's suggestion will be right as long chartProviders and uiProviders are instances of UiItemsProviders and not an array of them. Typescript would have been really helpful here.
