### ISSUE TITLE
Handling authenticationCallback errors 

### ISSUE THREAD

**Issue by mohsini172** [imodeljs/imodeljs#25]
When we are creating a listener for Global Events we have to provide an authentication callback. Some times due to connectivity issue the authentication callback that we are providing had to throw an error because it's failed to fetch the token. I'm getting an error of unhandled promise rejection from the iModelJs library. Is there any better way to handle this issue?

**Comment by Animagne** [comment]
The iModel Hub event listeners are only basic implementation of continuously listening for events. It expects that the provided authentication callback will manage all of the authentication related retries itself and if authentication callback fails, listeners are stopped to avoid continuously getting errors.

I will look into unhandled promise rejection though, as that should not happen.

**Comment by ramanujam-raman** [comment]
Can you subscribe to events that are specific to an iModel instead of global events. The latter requires special access and service accounts.

**Comment by ramanujam-raman** [comment]
Please let us know if you have issues with subscribing to per-iModel events - like I mentioned global events have very restricted access. Can you close this issue if the suggestion works for your case?

**Comment by mohsini172** [comment]
I have been able to subscribe on both global event and imodel events. Though there's still an issue with .createListener method. It was logging an issue unexpected JSON when using JSON.parse on global event. The main issue with that method is that it does not provide any callback when internal error occurs and deletes listener on its own. I switched to .getEvent method for time being.

**Comment by Animagne** [comment]
createListener method is only meant to provide a basic loop implementation. To cover all event listening scenarios this would require a few more additional callbacks making this method difficult to use. To have error handling when querying events, a loop should be implemented using repeated calls to getEvent method instead.
