### ISSUE TITLE
Hope to support byteStride and KHR_draco_mesh_compression for b3dm/glb format tiles. 

### ISSUE THREAD

**Issue by tony-tang** [imodeljs/imodeljs#264]
**GltfReader** can't support byteStride property in bufferView. It causes reality meshes to not be displayed. Hope to support byteStride. BufferView ref: 
https://github.com/KhronosGroup/glTF/blob/41657440949864444672b8a2776b7c5086ad90e5/specification/2.0/schema/bufferView.schema.json

**Comment by RBBentley** [comment]
The byteStride is supported here https://github.com/imodeljs/imodeljs/pull/205 hopefully will be completed soon.   This also has the draco support - but it is disabled until a future PR where we will move the decompression to a web worker (hopefully fairly soon) -- Do you have an example mesh I can test?

**Comment by tony-tang** [comment]
Thanks your reply.  Test meshes please refer to attachments. Please use tileset2.json, because imodel is not goog for multiple tileset.json.
[test_3dtiles_byteStride.zip](https://github.com/imodeljs/imodeljs/files/5573208/test_3dtiles_byteStride.zip)
[test_3dtiles_draco_compress.zip](https://github.com/imodeljs/imodeljs/files/5573219/test_3dtiles_draco_compress.zip)

**Comment by RBBentley** [comment]
Thanks --- I have tested and the byte stride works fine with your data. - I will also test draco when I work on that (in near future).
![image](https://user-images.githubusercontent.com/20863871/99800363-3ee42480-2b02-11eb-8f8f-4c8cbc4877fd.png)

**Comment by RBBentley** [comment]
Tony -- I'm looking at the tileset.json -- This should work - I'll get this resolved as well.

**Comment by tony-tang** [comment]
Great job! I've tested, it works fine now. About tileset.json, it works fine now. Looking forward to further solving the draco compression issue!

**Comment by RBBentley** [comment]
Thanks Tony --- BTW - the Draco is implemented but commented off in GltfReader.ts -- Its just too slow without webworker.
