### ISSUE TITLE
XYandZ difference with Point3d

### ISSUE THREAD

**Issue by Mitchpain** [imodeljs/imodeljs#28]
Is there a reason why we use XYandZ instead of Point3d?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: spatialToCartographic---imodeljs-frontend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/reference/imodeljs-frontend/imodelconnection/imodelconnection/spatialtocartographic/

**Comment by kabentley** [comment]
This method only requires an object that has members x,y,z. It does not require that it be of type Point3d.
