### ISSUE TITLE
How can I publish mobile terminal

### ISSUE THREAD

**Issue by DarrenWen** [imodeljs/imodeljs#29]
We are planning to use imodesjs on mobile terminal recently, but I have seen few materials on the network, could you please provide me with more learning materials on mobile terminal development

**Comment by kabentley** [comment]
Can you please elaborate on what you wish to achieve? When you say "mobile terminal" do you mean as a web app on a tablet (e.g. from Safari or Chrome), or do you mean an iPad or Android device (which?)

**Comment by DarrenWen** [comment]
> Can you please elaborate on what you wish to achieve? When you say "mobile terminal" do you mean as a web app on a tablet (e.g. from Safari or Chrome), or do you mean an iPad or Android device (which?)


Sorry, I have a problem with that, I mean I want to release an app that works on an android device or an apple device.But the project doesn't give much documentation on this.

**Comment by kabentley** [comment]
We are currently working on our (imminent) 1.0 release. After that we plan to focus on some of these topics that haven't been available yet.

In the meantime, I suggest you get your application working as an Electron desktop app. It will be mostly mechanical work to get a functioning desktop app working on mobile (with a few exceptions).
