### ISSUE TITLE
Where create sample projects can be viewed?

### ISSUE THREAD

**Issue by LabyrinthTechnology** [imodeljs/imodeljs#3]
Hi,

I requested to create [new sample project](https://imodeljs.github.io/iModelJs-docs-output/getting-started/sample-project/) and I received an e-mail the project and the iModel were created.

Where I can see (to list) the project (or more projects in future)? I expected it will be in my [ProjectWise projects list](https://connect.bentley.com/SelectProject/Index), but I see only the empty project, not iModel. Maybe I did wrong that I created the project with the requested name upfront (before the request was sent).

With regards,

  Jan

**Comment by roopsaini** [comment]
Hi Jan,

The project has been created for you in our test drive organization. There is a possibility that the project you created is your organization is “shadowing” the one we created for you. Can you search the project name using the Search tool? If you are still unable to find it, we can investigate further.  

![search](https://user-images.githubusercontent.com/34580471/47734701-d7b45880-dc38-11e8-8e91-53815a6795dc.png)

**Comment by LabyrinthTechnology** [comment]
Hi,

sorry for the delay, I was outside home for a few days. Yes, using search (and also it seems there was some delay, so the created project was not displayed in the list immediately) I was able to identify the project, marked as External.

![connect-projects](https://user-images.githubusercontent.com/8292864/47872251-60d0b880-de0e-11e8-8fd2-c13abf012729.jpg)

Is it correct I do not see any file inside the project?

I plan to play with examples and to study more how authentication and access to data work in API.

With regards,

  Jan

**Comment by roopsaini** [comment]
Hi Jan,

Great. You won't see a file but you should be able to see the iModel listed when you click on the iModel link on the project page.

![imodels](https://user-images.githubusercontent.com/34580471/47873276-c1e09800-ddde-11e8-89e6-7ce9d06c67fc.PNG)


Thanks,
Roop

**Comment by LabyrinthTechnology** [comment]
Thanks for your quick response!

> you should be able to see the iModel listed when you click on the iModel link on the project page.

Unfortunately iModel information is missing in my project details:

![project-details](https://user-images.githubusercontent.com/8292864/47875117-0176a680-de16-11e8-9d06-01dfb8941b1a.jpg)


Regards,

  Jan

**Comment by roopsaini** [comment]
Hi Jan,

We just checked the logs, and there seems to have been an error during registration. We just fixed it and you should see it now. We apologize for the inconvenience.

**Comment by LabyrinthTechnology** [comment]
Hi,

> We just fixed it and you should see it now. 

Yes, it works now, I see the project in my list:

![imodelhub-project](https://user-images.githubusercontent.com/8292864/47898411-0ff4aa80-de76-11e8-9c6f-3efc53155490.jpg)

> We apologize for the inconvenience.

No problem, thanks for your help! I treat it as an evaluation / testing period, when issues are expected. And when there are no issues, the testing has not been good enough :smirk:

Because I have the access to example data and I see it in the list and can access it using viewing demo application, I close this issue as solved.

With regards,

  Jan
