### ISSUE TITLE
ui-ninezone documentation

### ISSUE THREAD

**Issue by AndrewStraussHatch** [imodeljs/imodeljs#30]
Is there any documentation available on ui-ninezone? I see the sample app here (https://github.com/imodeljs/imodeljs/tree/master/ui/ninezone), but is there any actual documentation?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: iModel.js-API-Reference-Documentation---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/reference/

**Comment by DanEastBentley** [comment]
Andrew,

There are 4 iModel.js UI packages: ui-core, ui-components, ui-ninezone and ui-framework. ui-core & ui-components will be part of the 1.0 release. However, ui-ninezone and ui-framework are still in active development and will be available in a later release, which will include a ninezone sample application. 

If Hatch would like to work directly with Bentley as an early adopter, you will receive guidance on all UI packages and developing ninezone applications.

Dan

**Comment by calebmshafer** [comment]
@AndrewStraussHatch with the latest update of the iModel.js documentation, a section on [UI 9-Zone}(https://imodeljs.github.io/iModelJs-docs-output//learning/ui/ninezone/) has been added.

Let us know what you think.  Thanks!
