### ISSUE TITLE
Reality mesh performance issue

### ISSUE THREAD

**Issue by tony-tang** [imodeljs/imodeljs#316]
1. When network is good and a lot of reality tiles to load, iModel is very stutter. But when network is not good, it is not such lag (Maybe the loading and rendering are caused by the same thread). But Cesium is very smooth.
2. In the case of good network, when using the mouse wheel to zoom, it will be stutter, and FPS drops to 3.

Test mesh(Because the geometricError calculation is different between imodel and cesium, Please use the corresponding json):
1. imodel tileset json: http://35.243.109.237/imodel_tileset2.json
2. cesium tileset json: http://35.243.109.237/cesium_tileset2.json

**Comment by RBBentley** [comment]
Tony - I'm sorry for the late response.  I am (finally) working on this now -- would it be possible to restore the test cases?

Thanks much.

**Comment by RBBentley** [comment]
Tony - This should be corrected with https://github.com/imodeljs/imodeljs/commit/91fd811d423b7fd4a709c8d2081f7cc5a2a43979

I wasn't able to get your test files to replicate - but this removes an excessive amount of CPU work when the reality tiles were loading which I believe was the reason for the sluggish performance you noted.
