### ISSUE TITLE
How to change the viewport to a drawing selected from tree

### ISSUE THREAD

**Issue by shanekril** [imodeljs/imodeljs#32]
How can the viewport be updated to a selected drawing using the simple-viewer-app as an example code base? E.g. App.tsx has an event (onSelectionChanged) allowing the user to retrieve the view id of the selected drawing. I would like to use this view id to update the viewport to the selected drawing content.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Viewport---imodeljs-frontend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/reference/imodeljs-frontend/views/viewport/?term=viewport

**Comment by kabentley** [comment]
If you have a viewId, you can call:

```ts
const viewState = await Model.views.load(viewId);
```
then, call:

```ts
screenVp.changeView(viewState);
```

I will update [this article](https://imodeljs.github.io/iModelJs-docs-output/learning/frontend/views/?term=viewport) to show this.
