### ISSUE TITLE
A solution to the problem of merging multiple imodel files

### ISSUE THREAD

**Issue by DarrenWen** [imodeljs/imodeljs#34]
I downloaded the source code of imodeljs, and I found that there is an IModelImporter class that can merge and output two different imodel files.However, when I use this method for model merge presentation, I will report an error in the process of merging. Is there any detailed documentation about this class? Or what other ways can I realize the merging of multiple imodel files?Looking forward to your reply.

**Comment by pmconne** [comment]
The IModelImporter class is declared "alpha". It is under active development and documentation will remain incomplete until it stabilizes.
Here's a description of how release tags like "alpha" work: https://github.com/imodeljs/imodeljs/blob/master/docs/core/learning/guidelines/release-tags-guidelines.md

**Comment by scsewall** [comment]
Yes, the IModelImporter class is under active development and only handles a few scenarios right now. That is why it was marked with @alpha. For planning purposes, could you please give some details on your merging scenarios and what the starting conditions and desired ending conditions look like?

**Comment by DarrenWen** [comment]
> Yes, the IModelImporter class is under active development and only handles a few scenarios right now. That is why it was marked with "alpha". For planning purposes, could you please give some details on your merging scenarios and what the starting conditions and desired ending conditions look like?
Thanks scsewall:
After the modeling is completed, we need to see the final modeling effect, which requires merging multiple DGN files together to see the effect.But the merging process is too demanding on computer hardware and time consuming if the model size is too large.Therefore, recently we are trying to use IModelImporter of imodeljs to realize the merging of multiple imode files to solve the problems previously encountered.

**Comment by DarrenWen** [comment]
> The IModelImporter class is declared "alpha". It is under active development and documentation will remain incomplete until it stabilizes.
> Here's a description of how release tags like "alpha" work: https://github.com/imodeljs/imodeljs/blob/master/docs/core/learning/guidelines/release-tags-guidelines.md

Hi pmconne：
Thank you for reminding

**Comment by ColinKerr** [comment]
Darren, how are you converting your DGNs to iModel?  

We can merge multiple DGNs into one iModel using our iModel Bridges which also understand and convert data intelligently from some specific applications.  iModel Bridges don't invalidate the approach you are trying but you might find the bridges already do a lot of what you are looking to do.

**Comment by candcconsulting** [comment]
Darren, we have many projects which are federating dgn's from many applications as well as REVIT/SmartPlant etc.
If you would like to explore this avenue then please reach out to me …
glen.worrallatbentley.com

**Comment by calebmshafer** [comment]
Hey @DarrenWen, you probably received help from Glen (@candcconsulting ) already but I do want to highlight the new [iTwin Synchronizer](https://www.bentley.com/en/products/product-line/digital-twins/itwin-synchronizer) which allows you to run a growing number of iModel Bridges (dgn, rvt, etc) on your desktop. 

I'm going to close this issue but feel free to open a new one for specific issues.
