### ISSUE TITLE
Official provided examples of measurement error problems

### ISSUE THREAD

**Issue by DarrenWen** [imodeljs/imodeljs#35]
###  When I ran the official UI example, I found the following error when I opened imodel in local mode:

Plµgíñ 'MeasurePoints' vërsìøñ próblèms éñçòûñtërèd

Mòdùlê main ïs ñøt lòádèd Mòdùlê react ïs ñøt lòádèd Mòdùlê react-dom ïs ñøt lòádèd Mòdùlê redux ïs ñøt lòádèd Mòdùlê lodash ïs ñøt lòádèd Mòdùlê inspire-tree ïs ñøt lòádèd Mòdùlê react-dnd ïs ñøt lòádèd Mòdùlê react-dnd-html5-backend ïs ñøt lòádèd Mòdùlê react-redux ïs ñøt lòádèd!
How to solve this problem? Thank you

**Comment by calebmshafer** [comment]
@DarrenWen thanks for reporting this.  It was an issue with @bentley/webpack-tools package and the way modules were being loaded.  It should be fixed in the latest code.

Can you please verify that it is working now?  If it isn't, feel free to reopen this issue or file a new one.

Thanks!
