### ISSUE TITLE
Leaf links on the left side (under iModel.js Core Packages) don't work

### ISSUE THREAD

**Issue by mgooding** [imodeljs/imodeljs#36]
The links on the left side use the CamelCase class name in the URL which returns a 404. Editing the link to use the class name in lower case works.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: iModels---imodeljs-backend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output//reference/imodeljs-backend/imodels/

**Comment by calebmshafer** [comment]
Thanks @mgooding, we noticed this earlier today.  Working on a fix now, should be fixed today, tomorrow at the latest.

**Comment by calebmshafer** [comment]
A fix has been pushed.  Feel free to open a new issue if you see anything else.  Thanks!
