### ISSUE TITLE
Expiration emails

### ISSUE THREAD

**Issue by keithfin** [imodeljs/imodeljs#37]
There appears to be an issue with the email expiration logic. I received more than 150 "InspectTechTestProject is about to expire" emails over the span of two days. Each email was about 10 minutes apart.

**Comment by sainiroop** [comment]
There was an issue in our notification logic that caused emails to be sent out every 10 minutes for 24 hours. The process runs on the 20th of every month. The issue will be resolved before next month's expiration warnings.
