### ISSUE TITLE
How to view a local imodel file using iModelJs without connecting to ProjectWise server?

### ISSUE THREAD

**Issue by georgyfelix** [imodeljs/imodeljs#39]
I want to view an iModel which is stored in my local machine without uploading it to iModelHub using iModelJs.

**Comment by kabentley** [comment]
Have you looked at the [simple-viewer-app](https://github.com/imodeljs/simple-viewer-app) example?

**Comment by mato5** [comment]
I have the same problem, I have looked at the [simple-viewer-app](https://github.com/imodeljs/simple-viewer-app), but I was unable to find a working solution. When I tried to follow the example, I ended up coming across this issue - [Invalid iModelToken for PRC operation request](https://github.com/imodeljs/simple-viewer-app/issues/12).

**Comment by roopsaini** [comment]
As mentioned in [#10](https://github.com/imodeljs/simple-viewer-app/issues/10), the "offline mode" functionality is currently unavailable.

This is the official way to use data with iModel.js for dev purposes: 

1)	Get [Bentley View CONNECT edition](https://www.bentley.com/en/products/product-line/modeling-and-visualization-software/bentley-view) (it's free)*. 
2)	Open your model (eg. dgn, dwg).
3)	Click File -> _Publish i-model_.
4)	Check options _Create a single package_ and _iModel version 2.0_.
5)	Hit _Publish_.
6)	Go to the registration [dashboard](https://imodeljs.github.io/iModelJs-docs-output/getting-started/registration-dashboard/?tab=1).
7)	Click _New Project_.
8)	Select iModel source as _Local iModel File_.
9)	Choose .imodel file published in step 5 and hit _Submit_.
10)	You are all set.

It can take a few minutes to upload depending on the size of the file.
If your data is already in iModel 2.0 format, skip steps 1-5. 

\* iModel publishing is also available from MicroStation, PowerDraft, and nearly every other Bentley desktop application (details [here](https://communities.bentley.com/products/microstation/b/microstation_blog/posts/publishing-an-imodel-in-bentley-view)).
