### ISSUE TITLE
Not able to run the sample app

### ISSUE THREAD

**Issue by RWeill** [imodeljs/imodeljs#391]
Hello
command npm run start:servers says :

Error   |basic-viewport-app| Bad Request: Node.js version v14.15.1 is not within the range acceptable to imodeljs-backend: (>=10.16.0 <13.0)

Thanks for you help
Remy weill
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-started-(online-quick-start)---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/getting-started/online-quickstart/

**Comment by calebmshafer** [comment]
@RWeill iModel.js does not currently support Node 14.x. We are working on the support and will hopefully have it available soon.  #175 is the PR we're working to add that support.

**Comment by YeMengHua417** [comment]
I have noticed that imodeljs support solar and ambient, do we have plans to support more light source? like Point light source ,thanks!

**Comment by pmconne** [comment]
We don't have any immediate plans to add new light types, primarily because we haven't received any requests to do so.
