### ISSUE TITLE
Uploading Pointcloud Data into an Imodel based Platform

### ISSUE THREAD

**Issue by Stoupha** [imodeljs/imodeljs#40]
Hello, 
I've just discovered Imodel, and I'm thinking about developing a website that is based on Imodel api's, the website will serve to upload bim model and pointcloud data to help visualize construction development. Is it possible to do it using Imodel api's, uploading pointcloud data extension .las and bim model extension .ifc ?

**Comment by kabentley** [comment]
You will first need to [bridge](https://imodeljs.github.io/iModelJs-docs-output/learning/imodel-bridges/?term=bridge) your IFC data into an iModel. We are currently working on releasing the IFC bridge, but in the meantime you can first convert it to .DGN or .DWG and then run a bridge for it.

For point clouds, iModel.js supports [PNTs](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/PointCloud/README.md) format. You'll have to convert the .las data to that format and connect to the webserver hosting it. FWIW, the [Cesium Ion](https://cesium.com/cesium-ion/) service is intended for just that purpose.

**Comment by Stoupha** [comment]
Thanks for your response, regarding .dgn or .dwg data, I can convert them, but I will lose the data connection that makes the ifc model, or BIM in general, worth using. It will be just a 3D model without any information about the objects ... 
Can you keep me posted regarding this, and if there any solution in keeping the ifc model with its information ?

**Comment by LabyrinthTechnology** [comment]
Hi,

> Can you keep me posted regarding this

because your original question was about pointcloud data and this is about the maintaining object data during the transformation, I recommend to create a new post for this question.

Regards,

  Jan

**Comment by kabentley** [comment]
As I said, we're working on a direct IFC -> iModel bridge. 

But, the IFC -> DGN -> iModel path won't lose your property data. It's true that the IFC -> DGN converter generally turns the IFC classes to "dynamic" properties, so you're right, it won't be as good as the direct bridge. But the data won't be lost, and it isn't "just a 3d model". I suggested it since its a good way to get started with iModel.js for prototyping your website.

**Comment by kabentley** [comment]
BTW, the *real* problem with the (source application) -> IFC -> DGN -> iModel path is that it becomes very difficult to track changes through that labyrinth. One of iModel.js greatest virtues is it's connection to iModelHub to store changesets. The IFC bridge rectifies that issue to the extent possible. We expect to have it available in a few weeks.

Even better would be to bridge the data from the source application format.

**Comment by jalonob** [comment]
> Hola,
> acabo de descubrir Imodel, y estoy pensando en desarrollar un sitio web que esté basado en la API de Imodel, el sitio web servirá para cargar el modelo bim y los datos de pointcloud para ayudar a visualizar el desarrollo de la construcción. ¿Es posible hacerlo usando Imodel api, cargando la extensión de datos de pointcloud .las y la extensión de modelo bim .ifc?

Hi @Stoupha, I want to ask you if you could carry out the development of your website by transforming the ifc to imodels? How can I contact you?
