### ISSUE TITLE
When creating projects with own imodel file just keep loading.

### ISSUE THREAD

**Issue by jmbarbeiro** [imodeljs/imodeljs#41]
When trying to register a new projects with my own .imodel file created from publishing a single package of a 2.0 .idgn. the system just keeps spinning and projects don't get created. It is even not relevant the size of the file. At present I have 2 projects pending creation for a couple of days without success so far.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output//getting-started//

**Comment by mato5** [comment]
As of today I am unable to provide my own .imodel when registering a project.

**Comment by Josh-Schifter** [comment]
Yesterday we noticed a regression that caused the issue described by @jmbarbeiro.   For now, we have temporarily disabled the upload function while we work on a fix.  We expect the problem will be resolved shortly.  This issue will be updated when we have more information.

**Comment by Josh-Schifter** [comment]
We have corrected the problem.  Please try again now.
