### ISSUE TITLE
When trying to use the simple-viewer-app with own imodel it keeps giving Error 400

### ISSUE THREAD

**Issue by jmbarbeiro** [imodeljs/imodeljs#42]
I've tried several times to run the simple-viewer-app with my own imodel loaded through the registered projects and it keeps returning Error 400 Unautorized Client. unauthorized_client - Invalid scope for client. @Timestamp < DateTime('2019-08-30T11:01:40.588520Z') and RequestId='0HLP4PU9GMUMV:000003BB'

Could you please advise what could be the issue? I've done it well with the sample model previously so not  sure why I can't do it with my own imodel.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/getting-started/

**Comment by sainiroop** [comment]
Hi @jmbarbeiro,

Your app registration might be missing the _context-registry-service:read-only_ scope. It is currently not listed in the default scopes, but a fix for that is underway.
Could you please check your app registration in the [dashboard](https://imodeljs.github.io/iModelJs-docs-output/getting-started/registration-dashboard/) to verify this?

You can add the missing scope by switching over to "custom."

![custom](https://user-images.githubusercontent.com/6562563/64024779-c827c980-cb00-11e9-87e5-ffa732a07a04.png)

**Comment by calebmshafer** [comment]
@jmbarbeiro can you confirm if this fixed the unauthorized issue?

**Comment by maakkoush** [comment]
Am facing the same issue and already had the context-registry-service:read-only scope added but still the issue persisted. Any hints?

**Comment by sainiroop** [comment]
@maakkoush this issue occurs when your client requests a scope that's not listed in your app registration. Can you verify that the scopes in your configuration.ts (under common) match the scopes in your registration on the [dashboard](https://www.imodeljs.org/getting-started/registration-dashboard/)?

Scopes in client code:

![image](https://user-images.githubusercontent.com/6562563/72540483-7f21a900-3846-11ea-8c42-32c31439384d.png)

Scopes in app registration:

![image](https://user-images.githubusercontent.com/6562563/72540500-8943a780-3846-11ea-85e6-1d027f6f80a9.png)

**Comment by maakkoush** [comment]
Worked perfectly. Thanks.
