### ISSUE TITLE
Failed to run build via npm

### ISSUE THREAD

**Issue by hackneycrypto** [imodeljs/imodeljs#43]
Hi,
I am getting the following error when I try to run the build after installing npm.

Note: I had to install via `npm i npm@latest` because the standard `npm install` command was also causing an error.

I am trying to run on MacOS Majave (10.14.5 (18F132)).

Regards,
Stephen.

[2019-09-03T14_10_35_087Z-debug.log](https://github.com/imodeljs/imodeljs/files/3569884/2019-09-03T14_10_35_087Z-debug.log)

**Comment by sainiroop** [comment]
Hi @hackneycrypto,

Your log indicates you are using node v8.15.0. iModel.js requires node 10.x version as listed in the [Getting Started](https://imodeljs.github.io/iModelJs-docs-output/getting-started/#1-get-the-tools) page. However, we currently only support Windows and Linux. 

> Mac support will be coming in future updates so stay tuned... (from [#13](https://github.com/imodeljs/simple-viewer-app/issues/13))

**Comment by hackneycrypto** [comment]
OK, thanks. I will do that.
