### ISSUE TITLE
code example for ECSQL SELECT for sample viewer 

### ISSUE THREAD

**Issue by ctn227** [imodeljs/imodeljs#44]
I would like an code example of using ECSQL Select for the front end of the Simple viewer app. Thank you

**Comment by sainiroop** [comment]
Hi @ctn227,

I recently wrote a blog [post](https://medium.com/imodeljs/imodel-js-meets-csv-part-2-3-52535da19576) on this subject. 
In short, you can use the [query ](https://imodeljs.github.io/iModelJs-docs-output/reference/imodeljs-backend/ecdb/ecdb/query/?term=query) API from the frontend to run ECSql queries.

**Comment by ctn227** [comment]
I'm new at this. I would appreciate it if you could tell me where to add the below lines to the Sample Viewer code to get it to compile:
	  const query = ('SELECT ECInstanceId AS id FROM BisCore:PhysicalModel');
	  const compIDs = await imodel.queryPage(query);
Got "property 'queryPage' does not exist on type IModelConnection' when adding the above to simple-viewer-app-master\src\frontend\components\App.tsx "private _onClick"

**Comment by sainiroop** [comment]
Looks like queryPage was deprecated. Try using [query ](https://imodeljs.github.io/iModelJs-docs-output/reference/imodeljs-frontend/imodelconnection/imodelconnection/query/?term=query)instead: 

const rows = []
for await (const row of imodel.query("SELECT .. ")) {
    rows.push(row)
}

I'll update the post.

**Comment by ctn227** [comment]
Got this error with the above code.:
src/frontend/components/App.tsx(258,26): error TS2532: Object is possibly 'undefined'.

**Comment by sainiroop** [comment]
Could you please provide a screenshot of your code? 

My guess is you are making the call from a place where _imodel_ could still be undefined. If that's the case, either you can add your code within an _if (imodel) {}_ block:

```
if (imodel) {
  const rows = []
  for await (const row of imodel.query("SELECT .. ")) {
    rows.push(row)
  }
}
```

or call it after the _(!imodel)_ check in the [__onIModelSelected_ ](https://github.com/imodeljs/simple-viewer-app/blob/fa2d178bed44d664a7fc2298c5c5f05647a1e4b2/src/frontend/components/App.tsx#L139)call

**Comment by ctn227** [comment]
Calling it after the (!imodel) check works well!!! thank you.
What table do I use to get the category below:
![image](https://user-images.githubusercontent.com/55195963/64719137-a54ccc00-d495-11e9-8288-22bbada498db.png)
