### ISSUE TITLE
How to get a list of tables for a project

### ISSUE THREAD

**Issue by ctn227** [imodeljs/imodeljs#45]
For the Simple Viewer project, what table do I use to get the category below:
![image](https://user-images.githubusercontent.com/55195963/64720451-7dab3300-d498-11e9-9475-38af3a8c0d82.png)

**Comment by sainiroop** [comment]
Example: 

![image](https://user-images.githubusercontent.com/6562563/64721836-42f6ca00-d49b-11e9-8c74-3027ee7a3d15.png)

As mentioned in the blog [post](https://medium.com/imodeljs/imodel-js-meets-csv-part-2-3-52535da19576), I highly recommend using the [iModel Console](https://imodelconsole.bentley.com/) app to improve your understanding of ECSql.

Especially helpful when used in conjunction with the [ECSql tutorial](https://imodeljs.github.io/iModelJs-docs-output/learning/ecsql/?term=tutorial).

**Comment by ctn227** [comment]
Thank you!
