### ISSUE TITLE
A part of del is associated with Mysq

### ISSUE THREAD

**Issue by gkj123456** [imodeljs/imodeljs#458]
I upload an IFC file to the imoDelHub to generate the imodel. I want to associate a part of the model with the information in the Mysql data table. What should I do nex

**Comment by gkj123456** [comment]
A part of imodel associated with Mysql table

**Comment by pmconne** [comment]
I'm sorry, your question is very unclear. Would you mind posting it with more details to our [Discussions page](https://github.com/imodeljs/imodeljs/discussions)?
