### ISSUE TITLE
Feature request: Callback for event listener error

### ISSUE THREAD

**Issue by mohsini172** [imodeljs/imodeljs#46]
I have a listener service for imodelhub event and creating listener would a great method to use. But the issue is that when something went wrong the listener stops and there's no feedback if the listener is stopped. It would be great if we can provide a callback for error like for do for processGlobalEvent.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Global-Events---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/learning/imodelhub/globalevents/?term=global

**Comment by eligijusm** [comment]
As documentation indicates GlobalEvents are reserved for internal use in Bentley and will not work for 3rd party applications. I suggest looking at [regular iModel events](https://imodeljs.github.io/iModelJs-docs-output/learning/imodelhub/events/).
Let us know if you have same problems with regular events or they don't provide functionality you need.
