### ISSUE TITLE
Compiling errors with FileReaderRpcInterface 

### ISSUE THREAD

**Issue by ctn227** [imodeljs/imodeljs#47]
I got compile errors when trying to use your example in 
https://medium.com/imodeljs/imodel-js-meets-csv-part-1-3-79a8ffde51da

-------- Operation: Compile .tsc files --------
Errors:
src/common/FileReaderRpcImpl.ts(9,53): error TS2345: Argument of type 'typeof FileReaderRpcInterface' is not assignable to parameter of type 'RpcInterfaceDefinition<RpcInterface>'.
  Type 'typeof FileReaderRpcInterface' is missing the following properties from type 'RpcInterfaceDefinition<RpcInterface>': interfaceName, interfaceVersion
src/common/FileReaderRpcInterface.ts(8,95): error TS2345: Argument of type 'typeof FileReaderRpcInterface' is not assignable to parameter of type 'RpcInterfaceDefinition<FileReaderRpcInterface>'.
  Type 'typeof FileReaderRpcInterface' is missing the following properties from type 'RpcInterfaceDefinition<FileReaderRpcInterface>': interfaceName, interfaceVersion
src/common/rpcs.ts(16,2): error TS2304: Cannot find name 'FileReaderRpcInterface'.
src/frontend/components/App.tsx(20,38): error TS2307: Cannot find module '../common/FileReaderRpcInterface'.

FileReaderRpcInterface.ts
import { RpcInterface, IModelToken, RpcManager } from "@bentley/imodeljs-common";

//file reader interface for the frontend
export abstract class FileReaderRpcInterface extends RpcInterface {	
  public static types = () => [IModelToken];
  public static version = "1.0.0";  // The API version of the interface
  
  public static getClient(): FileReaderRpcInterface { return RpcManager.getClientForInterface(this); }
  public async fetchInfo (_token: IModelToken): Promise<any[]> { return this.forward.apply(this, arguments as any) as any;}
}

FileReaderRpcImpl.ts
import { RpcManager, IModelToken } from "@bentley/imodeljs-common";
import { FileReaderRpcInterface } from "../common/FileReaderRpcInterface";
import * as fs from "fs";
//import * as parse from "csv-parse/lib/sync";

// Implement FileReaderRpcInterface
export class FileReaderRpcImpl extends FileReaderRpcInterface {
  public static register() {RpcManager.registerImpl(FileReaderRpcInterface, FileReaderRpcImpl);}
  private _filePath = "assets/testdata.csv";
  

  public async fetchInfo(_token: IModelToken): Promise<any[]> {
    const data: any = fs.readFileSync(this._filePath, "utf8");
	//const info = parse(data, {delimiter: ",",columns: ["status", "component_id"]});
    //return info;
	return data;
  }
}

rpct.ts
import { RpcInterfaceDefinition, IModelReadRpcInterface, IModelTileRpcInterface, SnapshotIModelRpcInterface } from "@bentley/imodeljs-common";
import { PresentationRpcInterface } from "@bentley/presentation-common";
import {FileReaderRpcInterface} from "../common/FileReaderRpcInterface";

/**
 * Returns a list of RPCs supported by this application
 */
export default function getSupportedRpcs(): RpcInterfaceDefinition[] {
  return [
    IModelReadRpcInterface,
    IModelTileRpcInterface,
	FileReaderRpcInterface,
    PresentationRpcInterface,
    SnapshotIModelRpcInterface,
  ];
}

**Comment by sainiroop** [comment]
Hi @ctn227,

I have updated the code in all the posts to a stable version. Also, I have replaced all the code images with GitHub gists, so you can now copy-paste directly from the blog :)

Can you please get the latest code and try again?

**Comment by sainiroop** [comment]
You can find the entire source code [here](https://github.com/sainiroop/simple-viewer-app/tree/imodeljs-meets-csv).
And here's a [diff](https://github.com/sainiroop/simple-viewer-app/commit/8401151f79ebc34efa03bc2c9522d9c02ed05dda) against the original simple-viewer-app source.

**Comment by ctn227** [comment]
Thank you very much for your help.
