### ISSUE TITLE
upload my Imodel 

### ISSUE THREAD

**Issue by maoyankandanteng** [imodeljs/imodeljs#49]
![1](https://user-images.githubusercontent.com/23349116/68913126-43f6f100-0795-11ea-87ce-8c824c0d8df8.png)
![5](https://user-images.githubusercontent.com/23349116/68913131-48230e80-0795-11ea-8a50-f01eb4a53e81.png)

**Comment by maoyankandanteng** [comment]
now i can't find the choice of "local Imodel file",so how to register a new projects with my own .imodel file created from publishing a single package of a 2.0 .idgn

**Comment by williamkbentley** [comment]
We temporarily disabled this feature while we investigated and fixed the issue. The fix has been deployed and you should be able to again upload your .imodel file to start a test project.

**Comment by maoyankandanteng** [comment]
> We temporarily disabled this feature while we investigated and fixed the issue. The fix has been deployed and you should be able to again upload your .imodel file to start a test project.

**Comment by maoyankandanteng** [comment]
Due to the closing of the web page during the upload process, the project in the registration dashboard have been loaded all the time,like this below
![Uploading 微信截图_20191120092459.png…]()

**Comment by maoyankandanteng** [comment]
> Due to the closing of the web page during the upload process, the project in the registration dashboard have been loaded all the time,like this below
