### ISSUE TITLE
Are EC schema the same / compatible with older ones?

### ISSUE THREAD

**Issue by LabyrinthTechnology** [imodeljs/imodeljs#5]
Hi,

when reading documenation [EC schemas](https://imodeljs.github.io/iModelJs-docs-output/bis/ec/ec-schema/), I have not found any comparison or information about "compatibility" with existing EC schemas as used in V8i and CONNECT Edition products.

Questions that crossed my mind:

* Are EC schemas used in iModelJs the same? E.g. version information is based on 3 digits (I like an idea behing the digits meaning :-), but now 2 digits are used, so it seems the schemas itself developed into new version / syntax.
* Are schemas available also as XML?
* What about compatibility with existing schemas tool like Bentley Class Editor or iModel Schema Editor?
* What about compatibility with DGN storage? Now MicroStation is able to import EC schemas into DGN file, which creates self-contained repository (similar to iModel SQLite). Is such scenario applicable also for new EC schemas?

With regards,

  Jan

**Comment by LabyrinthTechnology** [comment]
> The new schema xml is compatible with the iModel Schema Editor (which will have a read only public beta release soon)

I downloaded Beta 2 and it looks nice! Will try this tool more later ;-)

**Comment by ColinKerr** [comment]
Jan, 
  The description of what has changed between EC2 and EC3 made it out onto the public imodel.js documentation site.  Check it out here: https://imodeljs.github.io/iModelJs-docs-output/bis/ec/differences-between-ec2-and-ec3/

Please let me know if you want more info.  I will enhance the docs.  If the current documentation is sufficient please close this issue.

**Comment by ColinKerr** [comment]
Closing, please reopen or create a new issue if you need more information.

Thanks
 - Colin
