### ISSUE TITLE
iModel Upload,outdated file

### ISSUE THREAD

**Issue by maoyankandanteng** [imodeljs/imodeljs#51]
@Josh-Schifter 
![微信截图_20191122103139](https://user-images.githubusercontent.com/23349116/69394190-4669c580-0d16-11ea-8eb3-7d14e7913bbe.png)
I am a novice. I have some problems when I register the project. Can you teach me，Thanks

**Comment by Josh-Schifter** [comment]
The upload only supports the iModel 2.0 format.  The error suggests you are using an older format.  See [this page](https://communities.bentley.com/products/microstation/b/microstation_blog/posts/publishing-an-imodel-in-bentley-view) for instructions on how to create iModel 2.0.

**Comment by calebmshafer** [comment]
@maoyankandanteng if you have any follow up questions/issues, please open a new issue.
