### ISSUE TITLE
rush install error

### ISSUE THREAD

**Issue by rahul606** [imodeljs/imodeljs#54]
"rush install" command is not successful on Mac OS NodeJS - v12.13.1
Error: Command failed: npm install --no-save @bentley/imodeljs-darwin-x64@1.
│ npm ERR! code E404
│ npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bentley%2fimodeljs-
│ npm ERR! 404 
│ npm ERR! 404  **'@bentley/imodeljs-darwin-x64@1.8.5' is not in the npm registr**
│ npm ERR! 404 **You should bug the author to publish it (or use the name yourse**

**Comment by ColinKerr** [comment]
iModel.js backends do not yet support MacOS, but we're working on it.

The list of currently supported platforms can be found here: https://imodeljs.github.io/iModelJs-docs-output/learning/supportedplatforms/

I'm sorry this has been an inconvenience for you.
