### ISSUE TITLE
Running test apps over SSL

### ISSUE THREAD

**Issue by aderderian** [imodeljs/imodeljs#55]
Hello I have configured a self-signed cert for my localhost and have a key/cert file. I noticed that the "start:webserver" command will start a core Bentley webserver which is a wrapper of express server. Is there a way to pass parameters to it for the keyfile and certfile locations? Looking at the code it does not look like it is leveraging those options at the moment. https://github.com/imodeljs/imodeljs/blob/master/core/webserver/src/WebServer.ts

I require SSL for my application. Thank you advance of any advice.

**Comment by aderderian** [comment]
Any updates here?

**Comment by calebmshafer** [comment]
hey @aderderian, the imodeljs-webserver is just a thin wrapper around express, only accepting 2 basic configurations, to provide a starting point to host a static iModel.js frontend application.  If you need to support SSL, I'd suggest using express directly to implement the frontend web server as you'll be able to take full advantage of their APIs.

**Comment by aderderian** [comment]
Thanks @calebmshafer. I did do that. To the point of adding 2 more args for keyfile and cert and passing them down to the express server. But it did not seem to work. It was some time ago I tried this, so I will need to go back and look at it again. This seems like something that should be added though right? Assuming I can figure it out, supporting SSL out of the box seems like a needed addition.

**Comment by calebmshafer** [comment]
I think it may be worth taking a look at [serve](https://www.npmjs.com/package/serve) or [serve-https](https://www.npmjs.com/package/serve-https) for those purposes.  They already support different configuration options and may be more what you're looking for in this case.

The @bentley/imodeljs-webserver package is doing something that many other packages already do well and the intent is to remove/deprecate this package in iModel.js 2.0. We'll be moving to a different dev server setup and recommending using [serve](https://www.npmjs.com/package/serve) to host a production optimized app locally.

**Comment by calebmshafer** [comment]
Closing as there are some alternatives to using the, now deprecated, @bentley/imodeljs-webserver package for handling this.
