### ISSUE TITLE
Converting a file from .3mx to .imodel

### ISSUE THREAD

**Issue by Tomek1592** [imodeljs/imodeljs#56]
Hi,

is there any chance to convert ContextCapture .3mx file to .imodel? I tried to convert .3mx model using Bentley View CONNECT Edition, but a produced .imodel or .bim model seems not to be recognized correctly by connect.bentley.com Design Review web viewer - there is just a skybox, nothing else. I just want to know if there is any chance to produce iModel recognizable format from .3mx (or maybe something converted from .3mx). Thanks in advance.

**Comment by Josh-Schifter** [comment]
Have you tried the reality data picker in the web viewer?  To open it, look for an icon on the right side that looks like a globe.  If you data was converted properly, there should be an entry there.

If that doesn't work, please give us some more details of the steps you are using to produce the iModel and get it into the viewer.

**Comment by Tomek1592** [comment]
@Josh-Schifter thank you for your response. Yes, there is an entry in Reality Data tab (globe icon) but with Bing Map only. When i move down and click Model Tree tab (tree icon) there is an entry with my model: Model_name.imodel, but that's it, no any sub trees.

How I produce an iModel:

1. I'm using Bentley View CONNECT Edition to convert .3mx model to an i-model. Here is the official article about publishing an imodel: [https://communities.bentley.com/products/microstation/b/microstation_blog/posts/publishing-an-imodel-in-bentley-view](url). I'm following this article while publishing.
2. When .imodel file is ready, I create a new Project in the Registration dashboard: [https://imodeljs.github.io/iModelJs-docs-output/getting-started/registration-dashboard/](url). Of course I'm loading .imodel file previously selecting the Local iModel File rather then the Bentley Example checkbox.
3. When project is created, I open it through: iModel Manager > iModels > Model_name.imodel and clicking the View button. Then, in a new browser tab my model appears: Design Review > Model_name.imodel > Baseline.
4. In the Saved Views tab there is only "Default - View 1" and in the 3D Models tab there is a checkbox and the Model_name.imodel. When I check this checkbox, I'm able to click the Enter iModel button. When I click it, my iModel is loaded, but without any real model in it, just a skybox.

I hope that my answer is comprehensive and thank you in advance!

![3D-models-tab](https://user-images.githubusercontent.com/10050454/70982065-a3a72b80-20b6-11ea-8d0f-0e8cbdc1011e.PNG)
![skybox-only](https://user-images.githubusercontent.com/10050454/70982081-abff6680-20b6-11ea-91f5-ab681769acc1.PNG)

**Comment by Pascal-Cloutier** [comment]
@Tomek1592, After a thorough investigation of potential options, regretfully I have to report that we cannot support Reality Data through the iModel.js developer portal at imodeljs.org.  The portal’s upload feature is a limited workflow intended specifically to support developers learning about iModel.js.  However, we do believe that reality data is an important aspect of Digital Twins.  We are working on solutions to support the publication of Reality Data.  If you are an existing Bentley user and are interested in learning more, please contact our support team.  Otherwise, stay tuned as we are looking to enable this workflow in the future.
