### ISSUE TITLE
extracting .bim file from local .imodel file

### ISSUE THREAD

**Issue by andgonro** [imodeljs/imodeljs#60]
Hello,

I have a .imodel 2.0 file generated from OpenPlant and I would like to extract the .bim file in order to be able to use 
const iModel: IModelDb = IModelDb.openSnapshot(MyImodelName);

is there a way to do this locally without connection to the iModelHub or do I need to go through the iModelHub and then the [imodel-snapshot](https://gist.github.com/wilmaier/0a6cec9b660478c4719e6c9aa70b133d#imodel-snapshot) tool?

**Comment by sebaztian0** [comment]
I did it using the I.dgn,  and the  Bentley DgnDb iModel Importer that come with the Bentley view connect to convert the file to. idgdb, then a change the extension to. Bim

**Comment by ramanujam-raman** [comment]
Please use the iTwin Synchronizer for this henceforth - https://www.bentley.com/en/products/product-line/digital-twins/itwin-synchronizer
