### ISSUE TITLE
Urgent Issue 

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#61]
I am getting following Error:
(node:61488) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'stack' on string 'Failed to discover URL for service identified by "iModelHubApi"'
    at RpcInvocation.fulfillRejected (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:145:26)
    at RpcInvocation.fulfillment.result.then (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:57:102)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:61488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:61488) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'stack' on string 'Failed to discover URL for service identified by "iModelHubApi"'
    at RpcInvocation.fulfillRejected (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:145:26)
    at RpcInvocation.fulfillment.result.then (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:57:102)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:61488) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'stack' on string 'Failed to discover URL for service identified by "iModelHubApi"'
    at RpcInvocation.fulfillRejected (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:145:26)
    at RpcInvocation.fulfillment.result.then (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:57:102)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:61488) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'stack' on string 'Failed to discover URL for service identified by "iModelHubApi"'
    at RpcInvocation.fulfillRejected (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:145:26)
    at RpcInvocation.fulfillment.result.then (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:57:102)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:61488) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'stack' on string 'Failed to discover URL for service identified by "iModelHubApi"'
    at RpcInvocation.fulfillRejected (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:145:26)
    at RpcInvocation.fulfillment.result.then (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:57:102)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
>

Please check do needfull
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Documentation-Overview---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/

**Comment by ashish752** [comment]
I followed the following Process:
1: Downloaded the Simple Viwer APP
2.Install all modules and create bently account and project
3.Change Config in common with new project and model name
4.Start servers by npm run start:servers
5.Hit localhost:3000 in browser and try to open sample imodel then getting the following error

(node:61488) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'stack' on string 'Failed to discover URL for service identified by "iModelHubApi"'
    at RpcInvocation.fulfillRejected (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:145:26)
    at RpcInvocation.fulfillment.result.then (D:\Ashish\simple-viewer-app-master\node_modules\@bentley\imodeljs-common\lib\rpc\core\RpcInvocation.js:57:102)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ashish752** [comment]
Is this for firewall which cannot allowed to download briefcase in localhost??
If Yes then please tell me URL so that I can bypass that URL

**Comment by ColinKerr** [comment]
what seems to be failing is the call to get the URL for the iModelHub which would then be used to download the URL.  The failing request should have a url like: https://buddi.bentley.com/WebService/GetUrl/?url=iModelHubApi&region=0

The result of this call will include the url for the iModelHub.

**Comment by ashish752** [comment]
I am getting the following response when hitting that URL:
{"request":{"requestId":"eb136cd3-b8ec-4cfa-a495-44e27a74928c","inputs":[{"name":"url","value":"iModelHubApi"},{"name":"region","value":"0"}]},"resultInfo":{"resultCount":1,"message":"Success!"},"result":{"url":"https://imodelhubapi.bentley.com"}}

Can you please check tell me the solution for this

**Comment by ColinKerr** [comment]
Do you have 'imjs_buddi_url' or 'imjs_buddi_resolve_url_using_region' set in your config?

**Comment by sainiroop** [comment]
@ashish752 , can you please share the contents of your config.json file (under lib/webresources)? I would leave out your client-id if you have one.

**Comment by ashish752** [comment]
{
  // -----------------------------------------------------------------------------------------------------------
  // Project and iModel (REQUIRED)
  // Must un-comment the lines below and set these variables before testing - create a new project and
  // iModel with the developer registration procedure here - https://git.io/fx8YP
  // -----------------------------------------------------------------------------------------------------------
   "imjs_test_project" : "Demo_01_Simple_Viewer",
  "imjs_test_imodel"  : "Demo_01_Simple_Viewer"
}

**Comment by ashish752** [comment]
is there any way to connect through phone so that we can discuss this issue

**Comment by ashish752** [comment]
Team I didnt able to run this plz help me

**Comment by calebmshafer** [comment]
What version of the iModel.js libraries is Simple Viewer App (SVA) using? Also, are you using the Simple Viewer App from the [iModel.js Samples repo](https://github.com/imodeljs/imodeljs-samples) or from a different repository?

**Comment by ashish752** [comment]
Yes i downloaded Ip from Simple Viewer App repo

**Comment by calebmshafer** [comment]
Is the repository you downloaded it from, https://github.com/imodeljs/simple-viewer-app?  Can you copy the "dependencies" from the package.json?

**Comment by ashish752** [comment]
I downloaded zip folder from that repo n install npm

**Comment by ashish752** [comment]
Same package.json i used

**Comment by calebmshafer** [comment]
Can you try downloading the [iModel.js Samples repo](https://github.com/imodeljs/imodeljs-samples) and testing the same thing from the "interactive-app/simple-viewer-app" folder?

The individual Simple Viewer App repo hasn't been updated in several months and has been archived.

**Comment by ashish752** [comment]
Can I try with new zip downloaded project Simple Viewer?

**Comment by ashish752** [comment]
What is the issue, can u please explain so that I can also go through that

**Comment by calebmshafer** [comment]
Yes, you can download a zip of the iModel.js Samples repository which contains the newer version of the Simple Viewer App and try it out.

I'm not sure what the issue is yet but wanted to see if you can reproduce the error with the latest code so we can narrow down what's causing the error.

In addition, can you provide the full steps you used to get the error?  Such as,

1. Download a zip of the Simple Viewer App repo
1. npm install the repo
1. Update the `src/common/config.json`
1. npm run build
1. npm run start:servers

**Comment by ashish752** [comment]
I also did the above mentioned steps.
In my ofc network some issue in electron package so i Install node modules in open network and replace that and tried to start servers.
Server started and in browser localhost opened.

At the time of when I clicked imdoel button after login gettin that error

**Comment by calebmshafer** [comment]
When you tried to install again, when on an open network, did you delete the `node_modules` directory first? Or just re-ran the `npm install`?

**Comment by ashish752** [comment]
Yes that is deleted and replace with open network downloaded node modules

**Comment by ashish752** [comment]
We can also set up meeting and i will show u the issue

**Comment by ashish752** [comment]
Hi Team I have followed the following Steps:
1.Download Zip Project from iModel.js Samples repo and Unzip that
2.Go to \imodeljs-samples-master\interactive-app\simple-viewer-app and paste node modules 
3.Cd \interactive-app\simple-viewer-app and command npm run build

Getting some error at build time
> simple-viewer-app@0.0.0 build D:\Projects\imodeljs-samples-master\interactive-app\simple-viewer-app
> buildIModelJsModule


-------- Operation: Compile .tsc files --------
Errors:
src/frontend/components/App.tsx(10,70): error TS2305: Module '"../../../../../../../Projects/imodeljs-samples-master/interactive-app/simple-viewer-app/node_modules/@bentley/presentation-frontend/lib/presentation-frontend"' has no exported member 'IFavoritePropertiesStorage'.
src/frontend/components/App.tsx(10,98): error TS2305: Module '"../../../../../../../Projects/imodeljs-samples-master/interactive-app/simple-viewer-app/node_modules/@bentley/presentation-frontend/lib/presentation-frontend"' has no exported member 'FavoriteProperties'.
src/frontend/components/App.tsx(10,118): error TS2305: Module '"../../../../../../../Projects/imodeljs-samples-master/interactive-app/simple-viewer-app/node_modules/@bentley/presentation-frontend/lib/presentation-frontend"' has no exported member 'FavoritePropertiesManager'.
src/frontend/components/App.tsx(154,20): error TS2339: Property 'favoriteProperties' does not exist on type 'typeof Presentation'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-viewer-app@0.0.0 build: `buildIModelJsModule`
npm ERR! Exit status 1

But if I run npm run:npm run start:servers
Backend server started but for localhost://3000 getting error 'cannot GET \'

**Comment by ashish752** [comment]
One Important thing:
In Open network everthing working fine
But in workspace firewall I m getting issue 

Can you do one thing list out all URLs like briefcase dowlaod and connection to Bentely Server so that I can checked all that URL in workspace and make open if required
