### ISSUE TITLE
Storing Logger

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#64]
How we can store all logger in text file
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Logging---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/common/logging/?term=logger

**Comment by calebmshafer** [comment]
Hi @fella752, iModel.js supports [Bunyan](https://www.npmjs.com/package/bunyan) as an additional logger which has the ability to output the logs to a file.

The documentation on how to configure it with the iModel.js [Logger](https://www.imodeljs.org/reference/bentleyjs-core/logging/logger/) is within the API reference docs of the [BunyanLoggerConfig](https://www.imodeljs.org/reference/logger-config/logging/bunyanloggerconfig/#logtobunyan).

Please let us know if there are any issues getting it setup.

**Comment by calebmshafer** [comment]
Closing and continuing the conversation in #66
