### ISSUE TITLE
Could not find a declaration file for module 'openid-client'

### ISSUE THREAD

**Issue by pkmishr** [imodeljs/imodeljs#65]
i am importing  "@bentley/imodeljs-clients-backend" and using OidcAgentClient class but when i build my project it throw  "error Command failed with exit code 2".

Error:
/@bentley/imodeljs-clients-backend/lib/oidc/OidcBackendClient.d.ts(6,58): error TS7016: Could not find a declaration file for module 'openid-client'. 'C:/<folder>/<projectname>/node_modules/openid-client/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/openid-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'openid-client';

After installation @type/openid-client 
it gives Issure must have a argument. Issure is genereic.

Reference: OidcBackendClient.d.ts
 discoverEndpoints(requestContext: ClientRequestContext): Promise<Issuer>

*using lerna and eslint

**Comment by ramanujam-raman** [comment]
I couldn't reproduce this issue in a new vanilla typescript project with minimal dependencies - see test code and package.json below. The code uses OidcAgentClient to fetch an access token. Perhaps you can set this code up in a brand new npm project to compare. 

Now, the version of openid-client that is currently being used didn't have the type definitions, so we do add that in to the project. This seems related to your problem. See if you can find the typedefinition in this location after an "npm install" - 

> node_modules\@bentley\imodeljs-clients-backend\lib\openid-client.d.ts

In anycase, the code and package you can try out below - let us know if that helps.

test.ts

```
import {ClientRequestContext} from "@bentley/bentleyjs-core";
import {AccessToken} from "@bentley/imodeljs-clients";
import { OidcAgentClient} from "@bentley/imodeljs-clients-backend";

class AgentTest {

  public static async runTest() {
    const agentConfig =  {
      clientId: "<your-client-id-here>",
      clientSecret: "<your-client-secret-here>",
      scope: "urlps-third-party context-registry-service:read-only imodelhub",
    };

    const oidcClient = new OidcAgentClient(agentConfig);
    const jwt: AccessToken = await oidcClient.getToken(new ClientRequestContext(""));
    console.log(`Access token is ${jwt.toTokenString()}`);
  }
}

AgentTest.runTest();
```

package.json
```

{
  "name": "tsplayground",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "build": "tsc",
    "start": "node ./build/test.js",
    "prestart": "npm run build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "10.14.1",
    "typescript": "^3.5.0"
  },
  "dependencies": {
    "@bentley/bentleyjs-core": "1.11.0",
    "@bentley/geometry-core": "1.11.0",
    "@bentley/imodeljs-clients": "1.11.0",
    "@bentley/imodeljs-clients-backend": "1.11.0"
  }
}

```

**Comment by jashminkaur** [comment]
@pkmishr I am not getting this error.
Please check your node version and install node modules again.
