### ISSUE TITLE
Link to Next lesson missing

### ISSUE THREAD

**Issue by sypkenssmit** [imodeljs/imodeljs#661]
For lesson 8 (changesummaryqueries) the link at the very bottom to the next lesson, lesson 9 is missing. Also on the pages for lessons 9, 10, and 11 the links to previous and next lesson are missing.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Querying-Change-Summaries---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/ecsqltutorial/changesummaryqueries/

**Comment by sypkenssmit** [comment]
Maybe the fix has not yet propagated to the public website? The issue does **not** appear to be fixed. On the pages for lesson 9, 10, and 11 the links at the bottom are still missing. For lesson 8 it only has a button to go back to lesson 7, not one to proceed to lesson 9.

**Comment by pmconne** [comment]
That's correct, @sypkenssmit - the docs will be republished with the fix soon. Reopened for tracking.

**Comment by calebmshafer** [comment]
The docs have been updated. Feel free to re-open if you're still seeing an issue.
