### ISSUE TITLE
Authetication

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#67]
Hi Team,
Is there any API for bently login, in that we pass userName and password and get token as response.
We dont want to use imdelSelector
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Authentication---imodeljs-clients-backend-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/reference/imodeljs-clients-backend/authentication/

**Comment by mgooding** [comment]
In iModel.js 1.12.0, you can use `OidcDesktopClient` for this purpose. It will spawn a web browser to authenticate the user, but if your scope includes "offline_access" it will cache that credential for 30 days so the authentication will be silent.

```
async function signInWithDesktopClient(config: OidcDesktopClientConfiguration): Promise<AccessToken> {
  const requestContext = new ClientRequestContext();
  const client = new OidcDesktopClient(config);
  await client.initialize(requestContext);

  return new Promise<AccessToken>((resolve, reject) => {
    client.onUserStateChanged.addListener((token) => {
      token ? resolve(token) : reject(new Error("Failed to sign in"));
    });
    client.signIn(requestContext)
      .catch((err) => reject(err));
  });
}
```

**Comment by fella752** [comment]
I am using this now

await launchIModelSelector({
      exe_path: "node_modules//@bentley//imodel-selector//lib//iModelSelector-win32-x64",
      client_id: clientId, only_signin: true, scope, response_type: "code",
    }).then((data) => imodelSelectorData = data).catch((alert) => {
      logError(`Error loading iModelSelector. ` + alert);
      return;
    });
    if (!imodelSelectorData) {
      logError("Login Failed");
      return;
    }
    await imodelSelectorData.getAccessToken()
      .then((data) => accessToken = data)
      .catch((alert) => {
        logError(`Unable to retrieve access token. ` + alert);
        return;
      });
  }

**Comment by fella752** [comment]
But i want some type of API where we send userName and password and in response it will give me token 
Is there any API or anything by that we can use? @mgooding

**Comment by fella752** [comment]
in which module this OidcDesktopClientConfiguration available as m getting error

**Comment by mgooding** [comment]
> in which module this OidcDesktopClientConfiguration available as m getting error

OidcDesktopClientConfiguration is in "@bentley/imodeljs-common" as of iModel.js 1.12.0.

> But i want some type of API where we send userName and password and in response it will give me token
> Is there any API or anything by that we can use? @mgooding

No, for security reasons we intentionally do not offer such an API for interactive applications. The silent sign-in offered by OidcDesktopClient is the closest we will offer.

An application running on a server could authenticate as an Agent, which involves using stored credentials. However, it would be dangerously insecure to work this way as a desktop application because it would involve distributing your client's credentials. We strongly recommend against this approach.

**Comment by wilmaier** [comment]
If you upgrade to using OidcDesktopClientConfiguration, you should be sure to update all @bentley dependencies in package.json to 1.12.0.  Also, @bentley/imodel-selector should be updated to 1.0.20.

**Comment by fella752** [comment]
ihave done that but getting error in OidcDesktopClient (cannot find name)

**Comment by fella752** [comment]
Actaully we have the following requirement  :

- Currently imodelSelecter started in web browser and stored credentails in system and then call unity to start
But we want to pass userName and password through unity app

**Comment by fella752** [comment]
Getting error in OidcDesktopClient after updating package.json dependecies

**Comment by mgooding** [comment]
> Actaully we have the following requirement :
> 
> * Currently imodelSelecter started in web browser and stored credentails in system and then call unity to start
>   But we want to pass userName and password through unity app

Per our security requirements, we cannot provide a recommended workflow with this behavior. Because an embedded web browser will not have the latest security updates and may be compromised, authentication must be done in the system web browser.

**Comment by mgooding** [comment]
> Getting error(cannot find ) in OidcDesktopClient after updating package.json dependecies

```
import { OidcDesktopClient } from "@bentley/imodeljs-backend";
import { OidcDesktopClientConfiguration } from "@bentley/imodeljs-common";
```

This should work on iModel.js 1.12.0. If you get an error with these imports, please post it.

**Comment by fella752** [comment]
Module '"../../../../../Projects/Hatch/iModelViewer/node/node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend"' has no exported member 'OidcDesktopClient'.ts(2305)

**Comment by fella752** [comment]
Dependency detail"
"dependencies": {
    "@bentley/bentleyjs-core": "1.12.0",
    "@bentley/geometry-core": "1.12.0",
    "@bentley/imodel-selector": " 1.0.20",
    "@bentley/imodeljs-backend": "1.12.0",
    "@bentley/imodeljs-clients": "1.12.0",
    "@bentley/imodeljs-clients-backend": "1.12.0",
    "@bentley/imodeljs-common": "1.12.0",
    "@bentley/logger-config": "^1.12.0",
    "@bentley/presentation-backend": "1.12.0",
    "@bentley/presentation-common": "1.12.0",
    "@types/bunyan": "^1.8.6",
    "@types/faker": "^4.1.9",
    "axios": "^0.19.2",
    "bunyan": "^1.8.12",
    "faker": "^4.1.0",
    "log4js": "^6.1.2",
    "pause": "^0.1.0",
    "protobufjs": "~6.8.8",
    "ws": "^6.2.1",
    "yargs": "^12.0.0"
  }

**Comment by mgooding** [comment]
Hmm, it's definitely exported in iModel.js 1.12.0. See:
https://github.com/imodeljs/imodeljs/blob/master/core/backend/src/imodeljs-backend.ts#L55
https://github.com/imodeljs/imodeljs/blob/master/core/backend/src/oidc/OidcDesktopClient.ts#L34

I'm guessing something is awry in your node_modules directory... I would probably blow it away and install packages again:
* Close any open instances of your iModelViewer backend.
* `rd /s /q node_modules` from the command line in your `Projects/Hatch/iModelViewer/node/` directory.
* Run `npm install` to reinstall dependencies then `npm run build`.
