### ISSUE TITLE
General question on project structure - lib directory serving assets

### ISSUE THREAD

**Issue by aderderian** [imodeljs/imodeljs#68]
This is just a general question on the directory structure chosen to serve the project assets from the "lib" directory. Is this a React.js convention perhaps? I find it confusing that lib would be the output directory for build assets which then are served from webresources. Could this be changed to a more common name like "dist". "src" and "dist" are pretty typical in JS dev. 

Again, not an issue. More of a comment.

**Comment by aderderian** [comment]
I am going to augment this with the note that this is all configurable through webpack and a person's own custom build pipe, but was wondering the teams thinking here. Thx

**Comment by aderderian** [comment]
I took a second look at this, and it seems the reasoning behind it is due to node modules typically having their assets served in a lib directory for linking to other modules. They also seem to use a dist directory for when not being used in a library fashion.

**Comment by calebmshafer** [comment]
Hey @aderderian, you're correct about our reasoning for putting it all under the `lib` directory, it is to consolidate all of the output for both backend and frontend parts of the app into a single directory.  It also matched how all of the library packages handle their output.

That being said, we do have some changes in progress for the iModel.js 2.0 release that will make it more closely match the [create-react-app conventions](https://create-react-app.dev/docs/deployment) where the assets that need to be deployed are all consolidated within the build directory.

**Comment by aderderian** [comment]
Thanks Caleb. Yes I reviewed other node modules and noticed they're structured this way as well. It threw me off since this is different than a library type project versus an actual application.

**Comment by calebmshafer** [comment]
@aderderian this recommended structure of a project has changed slightly based on the [iModel.js 2.0](https://www.imodeljs.org/changehistory/2.0.0/) release.  I'm going to close out this issue but if you have questions/issues with the new setup feel free to open a new one
