### ISSUE TITLE
Issues hosting front-end in existing site structure

### ISSUE THREAD

**Issue by aderderian** [imodeljs/imodeljs#69]
I leveraged the code in the sample apps, interactive-app/simple-viewer-app to embed a front-end in an existing site. I had to make the following customizations :

1. Pass a urlTemplate for locales to load in startup
```
var i8nOptions: I18NOptions = { urlTemplate: "myurl/xyz/lib/webresources/locales/{{lng}}/{{ns}}.json" };
var options: IModelAppOptions = { i18n: i8nOptions };

        IModelApp.startup(options);
```
2. Move the code in index.html into my own page with script tags and leverage the imjsmodulecdn tag to get scripts to load properly. Seems this not the best approach.
`data-imjsmodulecdn="myurl/xyz/lib/webresources/"`

--------
I am still having issues where some static resources in ui-core.js will not load due to the page trying to load them from the page directory versus a configured location.
`"../static/media/bentley-icons-generic-webfont.b9b6da7b.ttf"`
Also the config.json expects to be loaded from the same relative location and the page as well. 

Are there ways to configure these two items so they can be loaded from a separate directory? I wnt to have a page with a viewer on it, but move the scripts to a different folder location. Secondarily, I would like to make the config.json dynamically set, so I want to load it from a URL that is different than the current page directory. imodeljs-client.js does not take any path info.
```
try {
            const configRequest = new XMLHttpRequest();
            configRequest.open("GET", "config.json", false);
            configRequest.send();
            const configResponse = JSON.parse(configRequest.responseText);
            if (typeof configResponse !== "undefined")
                this.merge(configResponse);
        }
```

**Comment by aderderian** [comment]
Hey iModel team. Any insight on this one would be awesome. Thx!

**Comment by calebmshafer** [comment]
Hey @aderderian, apologizes for the delay in response, however with the recent release of iModel.js 2.0 some of the issues you referenced above have changed and hopefully solved.

With the basis of an iModel.js web app being react-scripts, you should now be able to leverage the `PUBLIC_URL` [configuration](https://create-react-app.dev/docs/advanced-configuration) environment variable to move loading of all assets managed by webpack/react-scripts to the different route.

In addition, the `config.json` requests have been removed in favor of react-scripts handling which is explained [here](https://create-react-app.dev/docs/adding-custom-environment-variables) and then also [here](https://github.com/imodeljs/create-react-app/blob/imodeljs/packages/react-scripts/README-imodeljs.md) with the modifications we made specifically for iModel.js.

That leaves the localization setup which actually remains the same as the solution you described.  In the future, we may potentially take advantage of the `PUBLIC_URL` environment variable but for now you'll still need to specify the `I18NOptions`
