### ISSUE TITLE
Issue in Auth Token

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#71]
Hi Team,
I am using imodelSelectorData for authorization but after first time that login screen is not comming, can you plz tell me where that auth token data is stored in my system.
So that I can remove and try to enter userName and password again?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: AccessToken---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/common/accesstoken/

**Comment by mgooding** [comment]
* Hit the Windows key, and enter "Credential Manager"
* Select Windows Credentials
* You should an entry along the lines of "Bentley.iModelJs.OidcTokenStore"

**Comment by fella752** [comment]
in Unity example project I already looged in through imdelSelector but not able to retry as its store and expiry date showing 29 feb
I am not able top find any entry in that location

**Comment by fella752** [comment]
Is there any way to get userName and password from app and store it in file, from file we can call imodelSelector for login to app?

**Comment by ramanujam-raman** [comment]
For use cases that involve **users** getting the application to act **on their behalf** to access a protected resource (like iModelHub), the OIDC implementation does not support supplying a hardcoded user name and password. This is referred to as  ["resource owner password credentials workflow"](https://www.scottbrady91.com/OAuth/Why-the-Resource-Owner-Password-Credentials-Grant-Type-is-not-Authentication-nor-Suitable-for-Modern-Applications) and most implementations consider it as too high of a security risk. 

As long as a web browser is available to the user, the authorization code flow that imodel.js currently supports should be sufficient and necessary to fetch the access token.
