### ISSUE TITLE
Logging With Unity

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#72]
Hi Team,
Is there any way to do bentely sign in through Unity?? 
It's done by imodelselector in desktop but I want to login through unity app
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Opening-an-iModel-via-the-IModelDb-class---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/backend/imodeldb/

**Comment by mgooding** [comment]
Do you mean you want to redirect the Bentley logging output to appear in Unity's console and log files? 

I haven't done this myself, but it looks like you would have a custom Bunyan logging callback to send the message over the RPC mechanism and spit it out with Debug.Log and friends. (I'm assuming you're using the same RPC scheme as imodel-unity-example).

**Comment by fella752** [comment]
Plz check edited comment above

**Comment by ramanujam-raman** [comment]
The authentication/authorization for Bentley hosted services is based on OpenID Connect / OAuth2.0. All iModel.js does is to provide convenience wrappers over existing open source JavaScript clients - like [oidc-client-js](https://github.com/IdentityModel/oidc-client-js) or [appauth-js] (https://github.com/openid/AppAuth-JS). You can perhaps search for similar clients that are used by other Unity applications?

**Comment by mgooding** [comment]
To follow up on Raman's answer, note that even if you use an alternative Unity OIDC client, it will have to work through a web browser. I suggest sticking with OidcDesktopClient or similar and saving yourself a lot of work for the same result.
