### ISSUE TITLE
Give some context to the documentation

### ISSUE THREAD

**Issue by manderson88** [imodeljs/imodeljs#74]
The documentation provided shows the immaturity of the API.  It is both fluid (changes) and lacking any information to make it useful.  Link the documentation to some code for better context.  This is especially important when you introduce new items to the API.  
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: BackstageItemUtilities---ui-framework-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/reference/ui-framework/backstage/backstageitemutilities/

**Comment by NancyMcCallB** [comment]
Hi, Mark,

Sorry for the delay in response! 

You are correct that the UI for iModel.js apps is very much under development. We have tagged it all as beta for that reason, and you can expect some breaking changes in iModel.js 2.0.

Your point about the poor documentation context is well-taken, though, and we're working to flesh that out for 2.0 and moving forward. 

We're happy to help if you have questions and welcome your feedback about specific areas of the documentation you think need clarifying.
