### ISSUE TITLE
Bentley Social Distancing App for Construction Crews?

### ISSUE THREAD

**Issue by dominicSeah** [imodeljs/imodeljs#75]
A lot of complaints and worries about how construction crews are not subject to lockdown and vulnerable due to need to work in close proximity.

How long would it take to write an app that tracks proximity between mobile phones on site? Building sites could distribute to site crew to help encourage/enforce social distancing.

Functionality:

1. App to be distributed to all visitors in addition to site crew.

2. Track distance between registered mobile phones. Duration, approx location.

3. If 2m distance is breached then a warning goes off on the affected phones. Logged and sent to site office / monitoring app.

The monitoring app would keep records so that if any of the site crew gets infected, the health service would be able to determine who would be at risk by rolling back the logs... Broad St pump-style?

Probably an imodel.js hackathon jobbie?

**Comment by pmconne** [comment]
Sounds useful. Doesn't sound like it requires or leverages iModel.js though.

**Comment by dominicSeah** [comment]
?? I thought that imodel.js was all very open to all things internet and better for rapid development.
What do you think would be needed instead?

**Comment by pmconne** [comment]
Rapid development of applications that interact with a digital twin, yes. Tracking distance between one mobile device and another doesn't involve a digital twin. Unless you wanted the mobile devices to send their locations to some other app where their locations could be visualized in the context of the digital twin - that sounds like two apps to me though.

**Comment by dominicSeah** [comment]
Yea... the proximity ranging would need some fancy signal processing footwork. Bluetooth API? If a device is close enough to pair then alarm goes off and the monitoring app logs the incident.

In any case, even if it isn't a good fit for imodel.js. Getting an app out there would be a PR coup for Bentley who can say 'we have your backs, guys... and look how quick we did it'
