### ISSUE TITLE
iModel Tree

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#76]
Team,
Is there any way to fetch iModel Tree data in Simple Viewer app, same as web App
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: iModel.js-Apps---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/app/

**Comment by grigasp** [comment]
The tree in simple-viewer-app is set up to show data using [presentation rules](https://www.imodeljs.org/learning/presentation/hierarchies/), specifically using this set of rules: https://github.com/imodeljs/imodeljs-samples/blob/master/interactive-app/simple-viewer-app/assets/presentation_rules/Default.PresentationRuleSet.xml. 

I'm not entirely sure what you mean by web app and/or which hierarchy in there. Assuming it's Design Review and the hierarchy is the Models Tree in Visibility Widget, it's using these presentation rules: https://github.com/imodeljs/imodeljs/blob/master/ui/framework/src/ui-framework/imodel-components/visibility-tree/Hierarchy.json. 

To replace simple-viewer-app's Default ruleset with Models Tree's ruleset:
1. Remove `{simple-viewer-app}/assets/presentation_rules/Default.PresentationRuleSet.xml`
2. Create `Default.PresentationRuleSet.json` in `{simple-viewer-app}/assets/presentation_rules/`
3. Copy the content of https://github.com/imodeljs/imodeljs/blob/master/ui/framework/src/ui-framework/imodel-components/visibility-tree/Hierarchy.json to the newly created `Default.PresentationRuleSet.json`.
4. Change `id` attribute from `"ui-framework/VisibilityTree"` to `"Default"`.

**Comment by fella752** [comment]
In Design review(connect-imodelweb.bentley.com): we are getting model hirechary of parent child. I want that model hierarchy data to use.
Is there any way or API to get that data in same format?

**Comment by grigasp** [comment]
As mentioned in the previous post, the models hierarchy there is created using presentation rules. If you use [those rules](https://github.com/imodeljs/imodeljs/blob/master/ui/framework/src/ui-framework/imodel-components/visibility-tree/Hierarchy.json) in combination with [PresentationTreeDataProvider](https://www.imodeljs.org/reference/presentation-components/tree/presentationtreedataprovider/), you can build the exact same hierarchy.

**Comment by fella752** [comment]
Hi Team,
I have added the rule JSON file and change the id as default.
After that I followed following thing:
1. getContentDescriptor(reqContext, contentRequestOptions, DefaultContentDisplayTypes.PropertyPane, this._keySet, undefined )

2.used getContent(reqContext, contentReqOption, descriptorData, this._keyset)
But for getContentDescriptor I am getting undefined value and so for getContent also

**Comment by grigasp** [comment]
The ruleset I pointed to doesn't have content rules for property grid - it's intended for a tree component, so it's expected for content requests to return no results.

After switching the rules you shouldn't even need to change any code - the `SimpleTreeComponent ` in simple-viewer-app should automatically pick that up. Just make sure id of the ruleset is set to "Default", same as in the old ruleset that you removed.

**Comment by fella752** [comment]
Can you please tell me the steps.
I followed the mentioned steps by you and call getContent function but data not comming

**Comment by fella752** [comment]
If there is any ECSql query to fetch model hierarchy data?

**Comment by grigasp** [comment]
Have a look at [this commit](https://github.com/grigasp/imodeljs-samples/commit/6d9182864953321c3ee6d4059edce49b0056afa4) where I basically followed the steps given in my first post in this thread.

**Comment by fella752** [comment]
I have tried that but not getting that data,
It will helpfull if you provide me ECSQL query so that I can use that

**Comment by fella752** [comment]
I want that data in unity example

**Comment by grigasp** [comment]
There's a lot of stuff going on behind the scenes when handling the rules - it's not possible to reconstruct the same hierarchy with just plain ECSQL. You can try using Elements' parent-child relationship, but it will not match exactly. Example:
- root Subject nodes: `SELECT UserLabel FROM bis.Subject WHERE Parent IS NULL`
- children of a Subject: `SELECT UserLabel FROM (SELECT UserLabel, Parent.Id as ParentId FROM bis.Subject UNION ALL SELECT UserLabel, Parent.Id AS ParentId FROM bis.InformationPartitionElement) WHERE ParentId = ?`

That gives you a models hierarchy. You can look at how the rules are set up to reconstruct it up to categories and elements.
