### ISSUE TITLE
Button in toaster

### ISSUE THREAD

**Issue by ashish-srivastava-dev** [imodeljs/imodeljs#763]
Can I add a button in Toaster message
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: ToastMessage---ui-framework-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/reference/ui-framework/notification/toastmessage/

**Comment by GerardasB** [comment]
> Can I add a button in Toaster message

Yes, you are looking for the [ReactNotifyMessageDetails](https://www.itwinjs.org/reference/ui-framework/notification/reactnotifymessagedetails/) which is accepted by the `messageDetails` of [ToastMessageProps](https://www.itwinjs.org/reference/ui-framework/notification/toastmessageprops/).

There is an usage example in _ui-test-app_:
https://github.com/imodeljs/imodeljs/blob/31b96284055241f6e770df94010bd9bbe7be2d88/test-apps/ui-test-app/src/frontend/appui/frontstages/component-examples/ComponentExamplesProvider.tsx#L697
