### ISSUE TITLE
IFC to Imodels

### ISSUE THREAD

**Issue by jalonob** [imodeljs/imodeljs#77]
Hi, I am trying to develop a website that allows me to read an IFC file and transform it into imodels, previously you were talking about a bridge developed by Bently that fulfills this function, my question is if this has already been developed? and how can i get it.

**Comment by jffmarkerbsi** [comment]
The iTwin Synchronizer (https://www.bentley.com/en/products/product-line/digital-twins/itwin-synchronizer) is a free application that can be used to convert a growing number of file formats, including IFC, and push to an iModel in the Hub for use with iModel.js.

**Comment by jalonob** [comment]
thanks friend for your reply
