### ISSUE TITLE
Bentley OpenID Connect error 400

### ISSUE THREAD

**Issue by craigt-mcs** [imodeljs/imodeljs#78]
Hi all, just updated with a pull of the latest 1.14 repo and now can't get any examples to work.  Errors, for Basic and Simple viewer.  I had all of these samples working on the previous repo\version.  Any direction would be nice, thanks
Error 400
unauthorized_client
Invalid redirect_uri
For more information please refer to SEQ logs using this query:
@Timestamp < DateTime('2020-04-12T21:09:56.739092Z') and RequestId='0HLUH35CVJG8S:00008C47'
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: 1.14.0-Change-Notes---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/changehistory/

**Comment by williamkbentley** [comment]
Hello. The signin redirect URI of your client should be "http://localhost:3000/signin-callback.html" - Including the .html.

**Comment by craigt-mcs** [comment]
Thanks for the reply, this is set as you called out above in the simple-viewer-app\src\common, this is as pulled from GitHub.  The unit tests fail on login as well.  Something has changed from the previous versions, I see the issue in the 1.14 version.  what am I missing?  thanks

**Comment by williamkbentley** [comment]
Can you ensure it is also registered, with .html, on the [registration dashboard](https://www.imodeljs.org/getting-started/registration-dashboard/) 
Ex:
![image](https://user-images.githubusercontent.com/38542573/79231254-cf9fa700-7e33-11ea-9e91-9984ac111041.png)

This change was implemented with this commit: https://github.com/imodeljs/imodeljs-samples/commit/9fae5f689fe2625c6f3200a808a496a732c453be

**Comment by craigt-mcs** [comment]
Please close this, finally resolved.  I switched the registration to include .html and did clean and rebuild and got past the Error 400.  thanks
