### ISSUE TITLE
Hi, how do I determine the type of an element, thank you

### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/imodeljs#79]
Hi. I am using frontend to get an element with instanceId. May I ask how to determine whether this element is a graphical element or a non-graphical element? Or how to determine the type of element. I can't get information from ElementProps that I can judge? thank you
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/getting-started//

**Comment by kabentley** [comment]
[ElementProps](https://www.imodeljs.org/reference/imodeljs-common/entities/entityprops/) has a member called `classFullName`. If it is a [GeometricElement](https://www.imodeljs.org/reference/imodeljs-common/entities/geometricelementprops/?term=geometrice) it will have a member named `geom`.

BTW, please ask this type of questions on [StackOverflow](https://stackoverflow.com/questions/tagged/imodeljs) with the tag #imodeljs

**Comment by shenshengyi** [comment]
OK,Thanks.
