### ISSUE TITLE
Category list

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#80]
Any API or ECSQL query to fetch iModel category list?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Categories---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/bis/intro/categories/

**Comment by mgooding** [comment]
`SELECT ECInstanceId FROM bis.Category` will get you the IDs of the Category elements in the iModel. See https://www.imodeljs.org/reference/imodeljs-backend/categories/category/ for reference on how to use the Category element.

**Comment by fella752** [comment]
Want to fetch attached category list @mgooding 
![P_20200418_191757](https://user-images.githubusercontent.com/59953408/79639626-91dfad00-81aa-11ea-9a18-ea44e95d30cf.jpg)

**Comment by mgooding** [comment]
The Category elements have the information you're looking for. Here's a snippet:
```
  iModel.withPreparedStatement("SELECT ECInstanceId FROM bis.Category", (stmt) => {
    while (stmt.step() === DbResult.BE_SQLITE_ROW) {
      const elementId = stmt.getValue(0).getId();
      const categoryName = iModel.elements.getElementProps(elementId).code.value;
      process.stdout.write(elementId + " - " + categoryName + "\n");
    }
  });
```

**Comment by kabentley** [comment]
If you just want spatial categories, you can use `bis.SpatialCategory`

**Comment by kabentley** [comment]
it may be helpful to look at how display-test-app does this:

https://github.com/imodeljs/imodeljs/blob/01619fb12c20d699429145bdc6c7258c1aa67c33/test-apps/display-test-app/src/frontend/IdPicker.ts#L241

**Comment by fella752** [comment]
@mgooding @kabentley 
I hv tried query for same Simple viewer app but getting more category value that is not coming in design review iModel category list in web view
![P_20200419_085746](https://user-images.githubusercontent.com/59953408/79678947-68606900-821e-11ea-864f-faf7a6430558.jpg)
![P_20200419_085726](https://user-images.githubusercontent.com/59953408/79678953-80d08380-821e-11ea-87c0-b8c663cea626.jpg)

**Comment by kabentley** [comment]
Please look at the code I linked above. It uses a more sophisticated query to get the name of only used categories. Everything you need is there.

BTW, in the future *please* use [StackOverflow](https://stackoverflow.com/questions/tagged/imodeljs) with the the tag #imodeljs to ask programming questions. GitHub Issues should only be used to report problems or suggest changes/enhancements.
