### ISSUE TITLE
Frontend best practices link leads to backend page

### ISSUE THREAD

**Issue by LabyrinthTechnology** [imodeljs/imodeljs#81]
A link in sentence "See best practices for writing frontend code and using ECSQL efficiently." leads to "Best Practices for Writing Backend Code" page.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: The-App-Frontend---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/frontend/

**Comment by calebmshafer** [comment]
Thanks @LabyrinthTechnology! We'll fix that sentence and the update will show up on the site soon.
