### ISSUE TITLE
Rush install ends with error

### ISSUE THREAD

**Issue by LabyrinthTechnology** [imodeljs/imodeljs#82]
Hi,

I tried (mostly just for curiosity) to build imodeljs using `rush install`, but it ends with error:

```
No matching version found for puppeteer@chrome-stable.

The latest release of puppeteer is "3.0.1".

Other releases are:
  * chrome-67: 1.3.0
  * chrome-68: 1.4.0
  * chrome-69: 1.6.2
  * chrome-70: 1.7.0
  * chrome-71: 1.9.0
  * chrome-72: 1.11.0
  * chrome-73: 1.12.2
  * chrome-74: 1.13.0
  * chrome-66: 1.1.1
  * chrome-65: 1.0.0
  * chrome-75: 1.15.0
  * chrome-76: 1.17.0
  * chrome-77: 1.19.0
  * chrome-78: 1.20.0
  * chrome-79: 2.0.0
  * chrome-81: 3.0.1
  * chrome-80: 2.1.0

If you need the full list of all 681 published versions run "$ pnpm view puppeteer versions".
Resolving: total 1973, reused 0, downloaded 1850
```

I guess the next error is mostly a consequence:

```
The command failed:
 C:\dev-iModelJS\imodeljs\common\temp\pnpm-local\node_modules\.bin\pnpm install 
--store C:\dev-iModelJS\imodeljs\common\temp\pnpm-store 
--no-lock 
--no-prefer-frozen-shrinkwrap 
--resolution-strategy fewer-dependencies
ERROR: Error: The command failed with exit code 1
```

Did I do anything wrong (e.g. not all prerequisites installed)? 

Unfortunately my knowledge of building workflow is still not good enough to identify the problem quickly :-(

My repo is cloned with not any modifications. Node 12.16.2, Windows Pro 64bit (latest with all updates installed), Chrome version 81.0.4044.122 (the latest).

Regards,

  Jan

**Comment by calebmshafer** [comment]
@LabyrinthTechnology the issue is puppeteer removed the 'chrome-stable' dist tag from npmjs which a few of our packages were relying on. An update has just been pushed to change the tag to 'chrome-80' (from the list in the error message) in a 1.14.1 release.

Could you pull and try again?  Thanks!

**Comment by LabyrinthTechnology** [comment]
@calebmshafer Thanks a lot for the committed fix.

`rush install` now runs fine and finished without error, so I close this issue.
