### ISSUE TITLE
Snapmode

### ISSUE THREAD

**Issue by jashminkaur** [imodeljs/imodeljs#83]
How you implement snapMode all features(like key-point and center intersection) in Web design review for iModel?
Is any available API

**Comment by bbastings** [comment]
You can specify the active snap settings by supplying a subclass of AccuSnap to IModelApp.startup and overriding the methods to get the current snap mode(s) and keypoint snap divisor:

`public static async startup(opts?: IModelAppOptions): Promise<void> {
  opts = opts ? opts : {};
  opts.accuSnap = new MyTestAppAccuSnap();
  await IModelApp.startup(opts);
...

class MyTestAppAccuSnap extends AccuSnap {
  private readonly _activeSnaps: SnapMode[] = [SnapMode.NearestKeypoint];
  public get keypointDivisor() { return 2; }
  public getActiveSnapModes(): SnapMode[] { return this._activeSnaps; }
}`

**Comment by jashminkaur** [comment]
Is there any API available that I can use to request snapMode(centre, keypoint etc) and get response same as web design review?

**Comment by bbastings** [comment]
You're going to need to provide more context...

If for example, your objective is to write an InteractiveTool that requires snapping, you would typically enable AccuSnap in your tool's onPostInstall:

`  public onPostInstall() {
    super.onPostInstall();
    IModelApp.accuSnap.enableSnap(true); // Enable AccuSnap for snapping to existing geometry
  }`

The learning documentation on PrimitiveTools may be helpful in this case.

**Comment by jashminkaur** [comment]
Want to use SnapRequestProps and snapResponseProps, can you help me to use this and fetch the response data?

**Comment by bbastings** [comment]
It is intended that you use AccuSnap as previously mentioned, it takes care of everything for you. The response is provided to you in the form of a HitDetail.

**Comment by jashminkaur** [comment]
Can you explain snapRequest and snapResponseProps keys and how we get it's value for any element/imodel??

SnapRequestProps{
id
testPoint
closePoint
worldToView
}
SnapResponseProps {
  snapMode
  heat
  geomType
  parentGeomType
  hitPoint
  snapPoint
  normal
  curve
  intersectCurve
  intersectId
}

**Comment by bbastings** [comment]
You still haven't provided any context or explained why you aren't using AccuSnap, but ok.

`export interface SnapRequestProps {
  id: Id64String; // Element id you want to snap to
  testPoint: XYZProps; // The world coordinate space point that was used as the locate point (ex. cursor location)
  closePoint: XYZProps; // The approximate world coordinate location on the geometry identified by testPoint  
  worldToView: Matrix4dProps; // Matrix4d that provides conversion between world coordinates and view coordinates
  viewFlags?: any; // Optional ViewFlags if display is filtered by GeometryClass.
  snapModes?: number[]; // Optional SnapMode(s) to evaluate for the supplied element to find the "best" snap. Default is Nearest
  snapAperture?: number; // Optional pick aperature size in pixels. Default is 12
  snapDivisor?: number; // Optional snap divisorfor SnapMode.NearestKeypoint. 1 for just end points, 2 for end points + mid point, etc. Default is 2.
  subCategoryId?: Id64String; // Optional, if you know the sub-category of the geometry identified by testPoint
  geometryClass?: GeometryClass; // Optional, if you know the GeometryClass of the geometry identified by testPoint
  intersectCandidates?: Id64Array; // Optional element ids of potential intersection candidates, required only for SnapMode.Intersection
  decorationGeometry?: DecorationGeometryProps[]; // Optional, for snapping to non-persistent geometry, you can ignore this.
}

export interface SnapResponseProps {
  status: number; // See SnapStatus
  snapMode?: number; // SnapMode that generated the "best" snap out of the requested snapModes
  heat?: number; // See SnapHeat
  geomType?: number; // See HitGeomType. What type of edge (or interior) geometry generated the snap 
  parentGeomType?: number; // See HitParentGeomType. The type of geometry surface, solid, mesh that was snapped to
  hitPoint?: XYZProps; // Point on element geometry in world coordinates closest to requested testPoint
  snapPoint?: XYZProps; // World coordinate snap point location
  normal?: XYZProps; // Surface normal (if applicable) in world coordinates at snapPoint 
  curve?: any; // GeometryQuery json (CurvePrimitive) if snap was to a curve/edge
  intersectCurve?: any; // GeometryQuery json (CurvePrimitive) to curve/edge of intersectId when requesting SnapMode.Intersection 
  intersectId?: string; // Element id that generated the "best" snap from the requested intersectionCandidates 
}`

**Comment by jashminkaur** [comment]
Doing AccuSnap implementation. Thank you.
