### ISSUE TITLE
SampleCode 

### ISSUE THREAD

**Issue by raomsv123** [imodeljs/imodeljs#84]
I see the config.json and configuration.ts files missing from the sample code from the update to GitHub.Is this by design due to change in the coding pattern .https://github.com/imodeljs/imodeljs-samples.git  
I cloned this repository while trying to follow the instructions to start off my first play with iMODEL/JS
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Documentation-Overview---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/

**Comment by calebmshafer** [comment]
@raomsv123 yes this is a design update with the iModel.js 2.0 release.  We're now supporting the create-react-app (CRA) [approach](https://create-react-app.dev/docs/adding-custom-environment-variables) of using `.env` files that are loaded into the app when it is built.  These variables will now be available at runtime in `process.env`.

One slight modification we made in addition to what is supported by CRA is to accept variables starting with `imjs_` (documented [here](https://github.com/imodeljs/create-react-app/blob/imodeljs/packages/react-scripts/README-imodeljs.md)).

One important note is this does not change the way you access them from the frontend code, you can still you `Config.App` as you previously did.

I'll update the [docs](https://github.com/imodeljs/imodeljs-samples/blob/master/README.md#interactive-app-development-setup) in the samples to reflect this change in setup.

**Comment by calebmshafer** [comment]
The sample [README](https://github.com/imodeljs/imodeljs-samples#interactive-app-development-setup) has been updated to reflect this change.  Thanks for pointing this out!

Let us know if you have any issues/additional questions with the new setup.
