### ISSUE TITLE
Tagging the releases

### ISSUE THREAD

**Issue by yogeshsajanikar** [imodeljs/imodeljs#85]
Will it be possible to tag the github repo? Currently it is not possible to checkout a particular release.

**Comment by calebmshafer** [comment]
@yogeshsajanikar, that's a good suggestion. We'll add this to our release process of new versions and backfill some of the previous versions as well.

**Comment by calebmshafer** [comment]
Added all release tags back to the 1.0.0 release and updated our release process to automatically tag.
