### ISSUE TITLE
Release Lock Should be Mentioned

### ISSUE THREAD

**Issue by zachzhu2016** [imodeljs/imodeljs#86]
I think the fact that the locks are released immediately after pushing changes should be mentioned in a comment for clarity.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Write-an-iModel-Bridge---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/writeabridge/

**Comment by pmconne** [comment]
Thanks - added a comment to that effect.
