### ISSUE TITLE
How can I combine several imodel 2.0 files into one file?


### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/imodeljs#87]
Hello, I am using imodel.js. How can I combine several imodel 2.0 files into one file?
thanks.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/getting-started/

**Comment by pmconne** [comment]
Use [IModelTransformer](https://github.com/imodeljs/imodeljs/blob/master/docs/learning/backend/IModelTransformation.md).
Please use github issues to report bugs, not ask questions. Questions are better directed to [StackOverflow](https://stackoverflow.com/tags/imodeljs) using the `imodeljs` tag.

**Comment by pmconne** [comment]
Hope this helped. Closing as "question, not issue".
