### ISSUE TITLE
How to copy elements from one model to another model?


### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/imodeljs#88]
Hello, I am using imodel.js. Is there a function similar to ElementCopyContext in imodel.js? Can be a model
The element in is copied to another model. Thank you.

* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/getting-started/

**Comment by pmconne** [comment]
[IModelCloneContext and IModelTransformer](url) are related APIs for cloning elements. Both are currently in `beta`, so documentation and some functionality (notably, using IModelTransformer to transform elements within the *same* iModel) are incomplete. Here's an example of copying an element into a different model using [IModelCloneContext](https://github.com/imodeljs/imodeljs/blob/master/core/backend/src/IModelCloneContext.ts):

```ts
function cloneElementToModel(existingElement: ElementState, destModel: Id64String): ElementProps {
  const context = new IModelCloneContext(existingElement.iModel);
  // Map the source model to the destination model
  context.remapElement(existingElement.model, destModel);
  return context.cloneElement(existingElement);
}
```

BTW, please use github issues to report bugs. Questions are better directed to [StackOverflow](https://stackoverflow.com/tags/imodeljs) using the `imodeljs` tag.

**Comment by pmconne** [comment]
Hope this helped. Closing as "question, not issue".

**Comment by shenshengyi** [comment]
> 
> 
> [IModelCloneContext and IModelTransformer](https://github.com/imodeljs/imodeljs/blob/master/docs/learning/backend/IModelTransformation.md) are relevant related APIs. Both are currently in `beta`, so documentation and some functionality (notably, using IModelTransformer to transform elements within the _same_ iModel) are incomplete. Here's an example of copying an element into a different model using [IModelCloneContext](https://github.com/imodeljs/imodeljs/blob/master/core/backend/src/IModelCloneContext.ts):
> 
> ```ts
> function cloneElementToModel(existingElement: ElementState, destModel: Id64String): ElementProps {
>   const context = new IModelCloneContext(existingElement.iModel);
>   // Map the source model to the destination model
>   context.remapElement(existingElement.model, destModel);
>   return context.cloneElement(existingElement);
> }
> ```
> 
> BTW, please use github issues to report bugs. Questions are better directed to [StackOverflow](https://stackoverflow.com/tags/imodeljs) using the `imodeljs` tag.

**Comment by shenshengyi** [comment]
Thank you very much for your answer, it helped me a lot.
