### ISSUE TITLE
Hello, I am using imodel.js. How can I combine several imodel 2.0 files into one file? thanks.

### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/imodeljs#89]
Hello, I am using imodel.js. How can I combine several imodel 2.0 files into one file?
thanks.

**Comment by LabyrinthTechnology** [comment]
Hi,

why do you repeat the same question several times (the same question is closed #87)?

Also, it was told clearly (and is also mentioned in [Contributing Guide](https://github.com/imodeljs/imodeljs/blob/dd54e2744010dcc3096de3a3f22b2e2dc57d767e/README.md)) that Github issues should be used for reporting bugs, but programming questions should be posted to [StackOverflow](https://stackoverflow.com/tags/imodeljs).

Regards,

  Jan
