### ISSUE TITLE
Pricing for iTwin subscription?

### ISSUE THREAD

**Issue by helgehes** [imodeljs/imodeljs#9]
I dont know if this is the right place to ask, but where can we find information about pricing for iTwin subscription?
Regards
Helge

**Comment by roopsaini** [comment]
We do not have pricing details available just yet but current and future information about iTwins will be found on www.bentley.com/iTwin. 

Thanks,
Roop

**Comment by roopsaini** [comment]
If you need more information on commercial terms right now, please send an email to imodel.js@gmail.com with your request.

**Comment by helgehes** [comment]
Okay thanks!
