### ISSUE TITLE
[Issue when testing web app] IModelReadRpcInterface.openForRead() is not available

### ISSUE THREAD

**Issue by tciuan** [imodeljs/imodeljs#93]
Hi All,

I followed steps on https://github.com/imodeljs/imodeljs-samples/blob/master/README.md to build interactive app devleopment setup. 

After I run npm run start:servers, the test web popped up and It worked well for me to log in. However, after I clicked open sample iModel, it shows  "IModelReadRpcInterface.openForRead() is not available"

Could you help me with this issue?

Thanks

**Comment by calebmshafer** [comment]
@tciuan it sounds like the backend may not have properly started. Can you try to launch the frontend and backend in two separate terminals?  For the backend run "npm run start:backend" and for the frontend try "npm run start:webserver".

This should let you better see the logs for both of the processes.

**Comment by JohnMajerle** [comment]
I ran into this exact same problem yesterday.  As a pure guess, I deleted everything and re-cloned the git repository from scratch.  Somehow that fixed the problem and I can run all three of the UI samples OK now.  Perhaps there was a problem with an npm dependency that was corrected when I started over?

**Comment by aderderian** [comment]
I can confirm this is an issue as well. After deleting basic-viewport-app directory and then re-cloning the issue went away.

**Comment by calebmshafer** [comment]
A number of others have run into this issue, it appears to be there's an inconsistency in how Rush is installing the dependencies. The workaround for now would be to do a `rush purge && rm -rf common/temp && rush install && rush clean && rush build --to simple-viewer-app`.  This completely cleans up the local installation and build to start from a clean slate.

We're working on making it easier to consume these samples by separating them into multiple repositories and not using Rush.  Those will be rolling out over the next several weeks so keep an eye out for them.

I'm going to close this issue but feel free to re-open, or create a new one in the [imodeljs-samples repo](https://github.com/imodeljs/imodeljs-samples/issues/new), if the workaround does not work. Thanks!
